# Generated by Django 6.0.6 on 2026-07-09 15:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qualification', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(default='APPLIED', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr_applicants',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('provider', models.CharField(blank=True, max_length=180, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hr_training_programs',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=80, unique=True)),
                ('marital_status', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employment_date', models.DateField()),
                ('department', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('employee_category', models.CharField(choices=[('ACADEMIC', 'Academic Staff'), ('TEACHER', 'Teacher'), ('HOD', 'Head of Department'), ('DEPUTY_HEAD', 'Deputy Headmaster'), ('HEADMASTER', 'Headmaster'), ('NON_TEACHING', 'Non-Teaching Staff'), ('FINANCE', 'Finance Officer'), ('ADMIN', 'Administrator'), ('SECRETARY', 'Secretary'), ('LIBRARIAN', 'Librarian'), ('LAB_TECH', 'Laboratory Technician'), ('SECURITY', 'Security Personnel'), ('DRIVER', 'Driver'), ('CLEANER', 'Cleaner'), ('HOSTEL', 'Hostel Staff')], max_length=30)),
                ('employment_type', models.CharField(default='Full-Time', max_length=80)),
                ('contract_type', models.CharField(default='Permanent', max_length=80)),
                ('qualification', models.CharField(blank=True, max_length=180, null=True)),
                ('specialisation', models.CharField(blank=True, max_length=180, null=True)),
                ('years_of_experience', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('next_of_kin', models.CharField(max_length=180)),
                ('next_of_kin_relationship', models.CharField(max_length=80)),
                ('next_of_kin_phone', models.CharField(max_length=50)),
                ('next_of_kin_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_profiles',
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('action_type', models.CharField(choices=[('WARNING', 'Warning'), ('SUSPENSION', 'Suspension'), ('INVESTIGATION', 'Investigation'), ('HEARING', 'Hearing'), ('APPEAL', 'Appeal')], max_length=30)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('outcome', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_actions', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hr_disciplinary_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('PART_TIME', 'Part-Time')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('document', models.FileField(blank=True, null=True, upload_to='hr/contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hr_employment_contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HRAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='Human Resources', max_length=80)),
                ('action', models.CharField(max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('panel', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('result', models.CharField(default='PENDING', max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='human_resources.applicant')),
            ],
            options={
                'db_table': 'hr_interviews',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('MATERNITY', 'Maternity Leave'), ('COMPASSIONATE', 'Compassionate Leave'), ('STUDY', 'Study Leave'), ('UNPAID', 'Unpaid Leave')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SUPERVISOR_APPROVED', 'Supervisor Approved'), ('HR_APPROVED', 'HR Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_applications', to='human_resources.employeeprofile')),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hr_approvals', to=settings.AUTH_USER_MODEL)),
                ('supervisor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_supervisor_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_leave_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(max_length=80)),
                ('kpi_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('promotion_recommendation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='human_resources.employeeprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_performance_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('QUALIFICATION', 'Qualification'), ('CERTIFICATE', 'Certificate'), ('NATIONAL_ID', 'National ID'), ('CV', 'CV'), ('PERFORMANCE', 'Performance Report'), ('DISCIPLINARY', 'Disciplinary Document')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='hr/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='human_resources.employeeprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_staff_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('closing_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='human_resources.vacancy'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=40)),
                ('allocated_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hr_leave_balances',
                'unique_together': {('employee', 'leave_type')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('absent', models.BooleanField(default=False)),
                ('biometric_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hr_staff_attendance',
                'ordering': ['-attendance_date'],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='hr/training/')),
                ('certificate_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='human_resources.employeeprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_records', to='human_resources.trainingprogram')),
            ],
            options={
                'db_table': 'hr_employee_training_records',
                'unique_together': {('employee', 'program')},
            },
        ),
    ]
