# Generated by Django 6.0.6 on 2026-07-10 14:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('default_annual_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('paid', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('includes_weekends', models.BooleanField(default=False)),
                ('includes_public_holidays', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hr_leave_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='hr/applicants/cv/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='applicant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='hr/applicants/supporting/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='archive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='assigned_classes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='next_of_kin_alt_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nssa_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='payment_method',
            field=models.CharField(default='BANK_TRANSFER', max_length=40),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pension_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='professional_body',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='professional_registration_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='professional_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/photos/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to='human_resources.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='teaching_subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='probation_period',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='salary_or_grade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='covering_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_leave_applications', to='human_resources.employeeprofile'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hr_decision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='remaining_leave_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='supervisor_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='hr/leave/'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='areas_for_improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee_self_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='performance_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('EMPLOYEE_REVIEW', 'Employee Review'), ('SUPERVISOR_REVIEW', 'Supervisor Review'), ('HR_REVIEW', 'HR Review'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='supervisor_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='training_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('ON_LEAVE', 'On Leave'), ('OFFICIAL_DUTY', 'Official Duty'), ('HALF_DAY', 'Half Day'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=30),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='access_level',
            field=models.CharField(choices=[('PUBLIC_HR', 'HR Visible'), ('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential')], default='RESTRICTED', max_length=30),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='evaluation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='status',
            field=models.CharField(default='PLANNED', max_length=30),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='venue',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='application_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(default='FULL_TIME', max_length=80),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='minimum_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='number_of_posts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEWED', 'Interviewed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='RECEIVED', max_length=40),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=80),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('SUPERVISOR_APPROVED', 'Supervisor Approved'), ('HR_APPROVED', 'HR Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('QUALIFICATION', 'Qualification'), ('CERTIFICATE', 'Certificate'), ('NATIONAL_ID', 'National ID'), ('CV', 'CV'), ('PERFORMANCE', 'Performance Report'), ('DISCIPLINARY', 'Disciplinary Document'), ('POLICE_CLEARANCE', 'Police Clearance'), ('MEDICAL', 'Medical Document'), ('LEAVE', 'Leave Document'), ('TRAINING', 'Training Certificate'), ('OTHER', 'Other Document')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SHORTLISTING', 'Shortlisting'), ('INTERVIEW', 'Interview'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hr_departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='human_resources.department'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='human_resources.department'),
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=180)),
                ('institution', models.CharField(blank=True, max_length=180, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=180, null=True)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('grade_or_classification', models.CharField(blank=True, max_length=120, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='hr/qualifications/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hr_employee_qualifications',
                'ordering': ['employee', '-date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='HRDocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='VIEW', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='human_resources.staffdocument')),
            ],
            options={
                'db_table': 'hr_document_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('employment_category', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_qualification', models.CharField(blank=True, max_length=180, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('approved_posts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='human_resources.department')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='human_resources.position')),
            ],
            options={
                'db_table': 'hr_positions',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='human_resources.position'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='human_resources.position'),
        ),
    ]
