# Generated by Django 6.0.6 on 2026-07-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
        ('subject_management', '0003_subject_department'),
        ('timetable_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='subject_management.subject')),
            ],
            options={
                'db_table': 'exam_coord_schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='timetable_engine.classroom')),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='exam_coordinator.examschedule')),
            ],
            options={
                'db_table': 'exam_coord_room_assignments',
                'unique_together': {('exam_schedule', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='ExamCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_candidates', to='student_registry.student')),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='exam_coordinator.examschedule')),
            ],
            options={
                'db_table': 'exam_coord_candidates',
                'unique_together': {('student', 'exam_schedule')},
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('session_type', models.CharField(choices=[('MID_TERM', 'Mid-Term Examination'), ('END_OF_TERM', 'End-of-Term Examination'), ('MOCK', 'Mock Examination'), ('PRACTICALS', 'Practicals Session')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='academic_structure.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='academic_structure.academicyear')),
            ],
            options={
                'db_table': 'exam_coord_sessions',
                'ordering': ['-academic_year', '-academic_term', 'name'],
            },
        ),
        migrations.AddField(
            model_name='examschedule',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exam_coordinator.examsession'),
        ),
        migrations.CreateModel(
            name='ExamSeating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('attendance_state', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused'), ('Withheld', 'Withheld')], default='Present', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocation', to='exam_coordinator.examcandidate')),
                ('room_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatings', to='exam_coordinator.examroomassignment')),
            ],
            options={
                'db_table': 'exam_coord_seatings',
                'ordering': ['seat_number'],
                'unique_together': {('room_assignment', 'seat_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('session', 'subject', 'date')},
        ),
    ]
