# Generated by Django 6.0.6 on 2026-07-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_factory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentsubjectresultsnapshot',
            new_name='document_fa_student_f162f0_idx',
            old_name='document_fa_student_f4e3d9_idx',
        ),
        migrations.RenameIndex(
            model_name='documentsubjectresultsnapshot',
            new_name='document_fa_subject_f2f5f0_idx',
            old_name='document_fa_subject_656a06_idx',
        ),
        migrations.RenameIndex(
            model_name='generateddocument',
            new_name='document_fa_documen_eb9ac8_idx',
            old_name='document_fa_documen_8697a8_idx',
        ),
        migrations.RenameIndex(
            model_name='generateddocument',
            new_name='document_fa_student_f200fd_idx',
            old_name='document_fa_student_6d6777_idx',
        ),
        migrations.RenameIndex(
            model_name='generateddocument',
            new_name='document_fa_student_b008e5_idx',
            old_name='document_fa_student_3264d5_idx',
        ),
        migrations.RenameIndex(
            model_name='generateddocument',
            new_name='document_fa_status_65652c_idx',
            old_name='document_fa_status_44e56e_idx',
        ),
    ]
