# Generated by Django 6.0.6 on 2026-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=180)),
                ('relationship', models.CharField(default='Guardian', max_length=80)),
                ('phone_number', models.CharField(max_length=40)),
                ('alternative_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=180, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'guardians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('pupil_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_no', models.CharField(max_length=80, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.TextField()),
                ('grade', models.CharField(max_length=80)),
                ('class_stream', models.CharField(max_length=80)),
                ('guardian_name', models.CharField(max_length=180)),
                ('guardian_phone', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('admission_date', models.TextField()),
                ('status', models.CharField(default='Active', max_length=40)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('grade_id', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('guardian_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('completed_on', models.TextField(blank=True, null=True)),
                ('status_changed_on', models.TextField(blank=True, null=True)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('transfer_destination', models.CharField(blank=True, max_length=180, null=True)),
                ('transfer_letter_no', models.CharField(blank=True, max_length=80, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pupils',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=80)),
                ('grade_id', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('class_teacher', models.CharField(blank=True, max_length=180, null=True)),
                ('class_teacher_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
    ]
