# Generated by Django 6.0.6 on 2026-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_textbook_loan_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pupil_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('form', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student_subjects',
                'managed': False,
            },
        ),
    ]
