# Generated by Django 6.0.6 on 2026-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_date', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(max_length=80)),
                ('reference_no', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=80)),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('amount_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade_id', models.IntegerField(blank=True, null=True)),
                ('payment_deadline', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fees_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterReceipt',
            fields=[
                ('master_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('master_receipt_no', models.CharField(max_length=80, unique=True)),
                ('batch_date', models.TextField()),
                ('generated_at', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_count', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_by', models.IntegerField(blank=True, null=True)),
                ('receipt_type', models.CharField(default='Fees', max_length=80)),
            ],
            options={
                'db_table': 'master_receipts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlinePaymentRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('pupil_id', models.IntegerField()),
                ('reference_no', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('bank_reference_no', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'online_payment_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pupil_id', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.TextField()),
                ('payment_method', models.CharField(max_length=80)),
                ('receipt_no', models.CharField(max_length=80, unique=True)),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('fee_id', models.IntegerField(blank=True, null=True)),
                ('recorded_by', models.IntegerField(blank=True, null=True)),
                ('master_receipt_id', models.IntegerField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.IntegerField()),
                ('pupil_id', models.IntegerField()),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'payment_allocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.IntegerField(unique=True)),
                ('receipt_no', models.CharField(max_length=80, unique=True)),
                ('issued_date', models.TextField()),
            ],
            options={
                'db_table': 'receipts',
                'managed': False,
            },
        ),
    ]
