# Generated by Django 6.0.6 on 2026-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pupil_id', models.IntegerField()),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('entry_type', models.CharField(default='Balance B/D', max_length=80)),
                ('source_term', models.CharField(blank=True, max_length=40, null=True)),
                ('source_year', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'balance_adjustments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TermBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('pupil_id', models.IntegerField()),
                ('fee_id', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('amount_billed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billed_on', models.TextField()),
                ('due_date', models.TextField()),
                ('status', models.CharField(default='Billed', max_length=40)),
            ],
            options={
                'db_table': 'term_bills',
                'managed': False,
            },
        ),
    ]
