# Generated by Django 6.0.6 on 2026-07-09 15:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_mgt_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='Inventory', max_length=80)),
                ('action', models.CharField(max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_mgt_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(default='Each', max_length=40)),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maximum_stock_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('WEIGHTED_AVERAGE', 'Weighted Average Cost')], default='WEIGHTED_AVERAGE', max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_capital_asset', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory_management.inventorycategory')),
            ],
            options={
                'db_table': 'inventory_mgt_items',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(max_length=50, unique=True)),
                ('count_type', models.CharField(choices=[('ANNUAL', 'Annual Stock Take'), ('PERIODIC', 'Periodic Stock Count'), ('CYCLE', 'Cycle Count'), ('SPOT', 'Spot Check')], max_length=20)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_mgt_stock_counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counted_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustment_recommended', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_management.inventoryitem')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory_management.stockcount')),
            ],
            options={
                'db_table': 'inventory_mgt_stock_count_lines',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=30, unique=True)),
                ('store_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_mgt_stores',
                'ordering': ['store_name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory_management.inventoryitem')),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory_management.store')),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory_management.store')),
            ],
            options={
                'db_table': 'inventory_mgt_stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_number', models.CharField(max_length=50, unique=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT', 'Adjustment'), ('COUNT_VARIANCE', 'Stock Count Variance'), ('WRITE_OFF', 'Write-Off')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('department', models.CharField(blank=True, max_length=120, null=True)),
                ('received_by', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_issued', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory_management.inventoryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory_management.store')),
            ],
            options={
                'db_table': 'inventory_mgt_stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockcount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory_management.store'),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=80, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory_management.inventoryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory_management.store')),
            ],
            options={
                'db_table': 'inventory_mgt_stock_batches',
                'ordering': ['expiry_date', 'received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=50, unique=True)),
                ('adjustment_type', models.CharField(choices=[('DAMAGED', 'Damaged Stock'), ('LOST', 'Lost Stock'), ('EXPIRED', 'Expired Stock'), ('CORRECTION', 'Stock Correction'), ('WRITE_OFF', 'Inventory Write-Off')], max_length=30)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('supporting_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory_management.inventoryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory_management.store')),
            ],
            options={
                'db_table': 'inventory_mgt_stock_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_recommendation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_alerts', to='inventory_management.inventoryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_alerts', to='inventory_management.store')),
            ],
            options={
                'db_table': 'inventory_mgt_reorder_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='inventory_management.store'),
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stock', to='inventory_management.inventoryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory_management.store')),
            ],
            options={
                'db_table': 'inventory_mgt_store_stock',
                'unique_together': {('store', 'item')},
            },
        ),
    ]
