# Generated by Django 6.0.6 on 2026-07-10 07:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('acquisition_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=150, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('useful_life', models.IntegerField(default=5, help_text='Useful life in years')),
                ('depreciation_method', models.CharField(choices=[('Straight-Line', 'Straight-Line'), ('Reducing Balance', 'Reducing Balance'), ('None', 'None')], default='Straight-Line', max_length=30)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='e.g. 15.00 for 15%', max_digits=5)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Use', 'In Use'), ('In Storage', 'In Storage'), ('Under Maintenance', 'Under Maintenance'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Disposed', 'Disposed'), ('Written Off', 'Written Off'), ('Stolen', 'Stolen')], default='Active', max_length=30)),
                ('location_name', models.CharField(blank=True, max_length=150, null=True)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_assets', to='human_resources.employeeprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'db_table': 'asset_register',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_department', models.CharField(blank=True, max_length=120, null=True)),
                ('assigned_location', models.CharField(blank=True, max_length=150, null=True)),
                ('date_assigned', models.DateField()),
                ('condition', models.CharField(default='Good', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_assignments', to='human_resources.employeeprofile')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'asset_assignments',
                'ordering': ['-date_assigned'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_logs', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_depreciation_logs',
                'ordering': ['-depreciation_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('disposal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('disposal_date', models.DateField()),
                ('method', models.CharField(choices=[('Sale', 'Sale'), ('Donation', 'Donation'), ('Write-Off', 'Write-Off'), ('Scrap', 'Scrap'), ('Loss', 'Loss'), ('Theft', 'Theft')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_disposals', to='human_resources.employeeprofile')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_disposals',
            },
        ),
        migrations.CreateModel(
            name='AssetInsurance',
            fields=[
                ('insurance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insured_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_insurance_policies',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Emergency', 'Emergency')], max_length=30)),
                ('maintenance_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('transfer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_location', models.CharField(max_length=150)),
                ('new_location', models.CharField(max_length=150)),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_transfers', to='human_resources.employeeprofile')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('verification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verification_date', models.DateField()),
                ('status_found', models.CharField(choices=[('Present', 'Present'), ('Missing', 'Missing'), ('Damaged', 'Damaged')], default='Present', max_length=30)),
                ('variance_notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='assets.asset')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'asset_verifications',
                'ordering': ['-verification_date'],
            },
        ),
    ]
