# Generated by Django 6.0.6 on 2026-07-10 07:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGuidanceSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('career_interests', models.TextField()),
                ('university_info', models.TextField(blank=True, null=True)),
                ('scholarship_info', models.TextField(blank=True, null=True)),
                ('assessment_notes', models.TextField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_sessions', to='human_resources.employeeprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_sessions', to='student_registry.student')),
            ],
            options={
                'db_table': 'career_guidance_sessions',
            },
        ),
        migrations.CreateModel(
            name='CounsellingAppointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='human_resources.employeeprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_appointments', to='student_registry.student')),
            ],
            options={
                'db_table': 'counselling_appointments',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='CounsellingCase',
            fields=[
                ('case_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_no', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Academic', 'Academic Counselling'), ('Behavioural', 'Behavioural Counselling'), ('Personal', 'Personal Counselling'), ('Career', 'Career Guidance'), ('Social', 'Social Counselling')], max_length=50)),
                ('description', models.TextField()),
                ('severity_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk'), ('Critical', 'Critical Risk')], default='Low', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Follow-Up Required', 'Follow-Up Required'), ('Closed', 'Closed'), ('Referred', 'Referred')], default='Open', max_length=30)),
                ('date_opened', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselling_cases', to='human_resources.employeeprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_cases', to='student_registry.student')),
            ],
            options={
                'db_table': 'counselling_cases',
                'ordering': ['-date_opened', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounsellingInterventionPlan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('Academic', 'Academic Improvement'), ('Behavioural', 'Behavioural Support'), ('Emotional', 'Emotional Support'), ('Social', 'Social Intervention')], max_length=30)),
                ('objectives', models.TextField()),
                ('activities', models.TextField()),
                ('review_date', models.DateField()),
                ('responsible_person', models.CharField(max_length=150)),
                ('progress_notes', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='counselling.counsellingcase')),
            ],
            options={
                'db_table': 'counselling_interventions',
            },
        ),
        migrations.CreateModel(
            name='CounsellingParentMeeting',
            fields=[
                ('meeting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('participants', models.TextField()),
                ('notes', models.TextField()),
                ('actions_taken', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_meetings', to='counselling.counsellingcase')),
            ],
            options={
                'db_table': 'counselling_parent_meetings',
            },
        ),
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(blank=True, null=True)),
                ('session_notes', models.TextField(help_text='Detailed notes on counselling session (Strictly confidential)')),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=25)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counselling.counsellingcase')),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'counselling_sessions',
                'ordering': ['date', 'session_number'],
            },
        ),
    ]
