# Generated by Django 6.0.6 on 2026-07-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelNotice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('published_date', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'hostel_notices',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_code', models.CharField(max_length=50, unique=True)),
                ('hostel_name', models.CharField(max_length=100)),
                ('hostel_type', models.CharField(choices=[('BOYS', 'Boys Hostel'), ('GIRLS', 'Girls Hostel'), ('MIXED', 'Mixed Hostel')], default='MIXED', max_length=40)),
                ('capacity', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=40)),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_hostels', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hostels',
            },
        ),
        migrations.CreateModel(
            name='HostelAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('time_slot', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Sick', 'Sick'), ('Excused', 'Excused')], max_length=40)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_attendance', to='student_registry.student')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hostel_attendance',
            },
        ),
        migrations.CreateModel(
            name='HostelBed',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=40)),
                ('current_occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_bed_allocations', to='student_registry.student')),
            ],
            options={
                'db_table': 'hostel_beds',
            },
        ),
        migrations.CreateModel(
            name='HostelDiscipline',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_date', models.TextField()),
                ('incident_description', models.TextField()),
                ('action_taken', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_notified', models.IntegerField(default=0)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_discipline_records', to='student_registry.student')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'hostel_discipline',
            },
        ),
        migrations.CreateModel(
            name='HostelFeeRecord',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_type', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_charged', models.TextField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Unpaid', max_length=40)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_fees', to='student_registry.student')),
            ],
            options={
                'db_table': 'hostel_fee_records',
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Maintenance', 'Under Maintenance'), ('Closed', 'Closed')], default='Available', max_length=40)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'db_table': 'hostel_rooms',
            },
        ),
        migrations.CreateModel(
            name='HostelMaintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=40)),
                ('reported_date', models.TextField()),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='hostel.hostelbed')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='hostel.hostel')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_maintenance', to='student_registry.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='hostel.hostelroom')),
            ],
            options={
                'db_table': 'hostel_maintenance',
            },
        ),
        migrations.CreateModel(
            name='HostelInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(default='Good', max_length=50)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hostel.hostel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hostel.hostelroom')),
            ],
            options={
                'db_table': 'hostel_inventory',
            },
        ),
        migrations.AddField(
            model_name='hostelbed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.hostelroom'),
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('boarding_date', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Vacated', 'Vacated')], default='Active', max_length=40)),
                ('guardian_notified', models.IntegerField(default=0)),
                ('fee_posted', models.IntegerField(default=0)),
                ('created_at', models.TextField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostel')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='student_registry.student')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelbed')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelroom')),
            ],
            options={
                'db_table': 'hostel_allocations',
            },
        ),
        migrations.CreateModel(
            name='HostelTransfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_allocation_id', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('transfer_date', models.TextField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.employeeprofile')),
                ('new_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelbed')),
                ('new_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('new_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelroom')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_transfers', to='student_registry.student')),
            ],
            options={
                'db_table': 'hostel_transfers',
            },
        ),
        migrations.CreateModel(
            name='HostelVisitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=180)),
                ('relationship', models.CharField(max_length=100)),
                ('visit_date', models.TextField()),
                ('time_in', models.TextField()),
                ('time_out', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed (Checked Out)')], default='Pending', max_length=40)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitors', to='human_resources.employeeprofile')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_visitors', to='student_registry.student')),
            ],
            options={
                'db_table': 'hostel_visitors',
            },
        ),
    ]
