# Generated by Django 6.0.6 on 2026-07-10 10:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        ('inventory_management', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'medical_conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='Medical', max_length=80)),
                ('action', models.CharField(max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('chronic_conditions', models.TextField(blank=True, null=True)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('long_term_medication', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('medical_aid_information', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=180)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=80, null=True)),
                ('emergency_contact_phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='profiles', to='medical.medicalcondition')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='human_resources.employeeprofile')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='student_registry.student')),
            ],
            options={
                'db_table': 'medical_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMERGENCY', 'Medical Emergency'), ('PARENT_CONTACT', 'Parent Contact Required'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('FOLLOW_UP', 'Follow-Up Appointment'), ('IMMUNISATION_DUE', 'Immunisation Due'), ('REFERRAL', 'Referral Appointment')], max_length=40)),
                ('message', models.TextField()),
                ('channel', models.CharField(default='PORTAL', max_length=30)),
                ('status', models.CharField(default='QUEUED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_notifications', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalEmergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=50, unique=True)),
                ('incident_date', models.DateField()),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('INJURY', 'Injury'), ('ALLERGIC_REACTION', 'Allergic Reaction'), ('SEVERE_ILLNESS', 'Severe Illness'), ('SPORTS_INJURY', 'Sports Injury'), ('MEDICAL_EMERGENCY', 'Medical Emergency')], max_length=40)),
                ('description', models.TextField()),
                ('treatment', models.TextField(blank=True, null=True)),
                ('referral_status', models.CharField(default='NOT_REFERRED', max_length=40)),
                ('parent_notification_status', models.CharField(default='PENDING', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_emergencies_handled', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencies', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_emergencies',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('SICK_NOTE', 'Sick Note'), ('CLEARANCE', 'Medical Clearance Letter'), ('REFERRAL', 'Referral Letter'), ('REPORT', 'Medical Report')], max_length=30)),
                ('issued_date', models.DateField()),
                ('summary', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='medical/certificates/')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_certificates',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAttendanceExcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excuse_type', models.CharField(choices=[('MEDICAL_LEAVE', 'Medical Leave'), ('HOSPITALISATION', 'Hospitalisation'), ('EXCUSED_ABSENCE', 'Excused Absence')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('attendance_updated', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_excuses', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_attendance_excuses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(max_length=50, unique=True)),
                ('appointment_type', models.CharField(choices=[('FOLLOW_UP', 'Follow-Up Visit'), ('SPECIALIST', 'Specialist Appointment'), ('ROUTINE', 'Routine Check-Up')], max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_appointments',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ImmunisationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=150)),
                ('vaccination_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=180, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=120, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immunisations', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_immunisations',
                'ordering': ['next_due_date', '-vaccination_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(max_length=50, unique=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('medication_prescribed', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('TREATED', 'Treated'), ('FOLLOW_UP', 'Follow-Up Required'), ('REFERRED', 'Referred'), ('SICK_BAY', 'Admitted to Sick Bay'), ('CLOSED', 'Closed')], default='TREATED', max_length=30)),
                ('confidential_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_visits_handled', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_visits', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_clinic_visits',
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_number', models.CharField(max_length=50, unique=True)),
                ('referral_date', models.DateField()),
                ('referral_type', models.CharField(choices=[('LOCAL_CLINIC', 'Local Clinic'), ('HOSPITAL', 'Hospital'), ('SPECIALIST', 'Specialist'), ('PSYCHOLOGIST', 'Psychologist'), ('COUNSELLOR', 'Counsellor')], max_length=40)),
                ('institution', models.CharField(max_length=180)),
                ('reason', models.TextField()),
                ('outcome', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_referrals',
                'ordering': ['-referral_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_code', models.CharField(max_length=50, unique=True)),
                ('medicine_name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expiry_date', models.DateField()),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=180, null=True)),
                ('barcode', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_medications', to='inventory_management.inventoryitem')),
            ],
            options={
                'db_table': 'medical_medications',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dispensed_date', models.DateField()),
                ('clinic_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='medical.clinicvisit')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_dispensed', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='medical.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_dispenses', to='medical.medicalprofile')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_prescribed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_medication_dispenses',
                'ordering': ['-dispensed_date'],
            },
        ),
        migrations.CreateModel(
            name='SickBayAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('bed_number', models.CharField(max_length=50)),
                ('admission_time', models.DateTimeField()),
                ('discharge_time', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('treatment_notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sick_bay_admissions', to='medical.medicalprofile')),
            ],
            options={
                'db_table': 'medical_sick_bay_admissions',
                'ordering': ['-admission_time'],
            },
        ),
    ]
