# Generated by Django 6.0.6 on 2026-06-11 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(max_length=80)),
                ('full_name', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Administrator', 'Administrator'), ('Headmaster', 'Headmaster'), ('Headmaster / Headmistress', 'Headmaster / Headmistress'), ('Bursar / Accounts Clerk', 'Bursar / Accounts Clerk'), ('Accountant', 'Accountant'), ('Registrar / Office Clerk', 'Registrar / Office Clerk'), ('Teacher', 'Teacher'), ('Librarian', 'Librarian'), ('Parent', 'Parent'), ('Student', 'Student')], default='Teacher', max_length=80)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
