# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_staff_admission_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Super Admin", "Super Admin"),
                    ("Administrator", "Administrator"),
                    ("Headmaster", "Headmaster"),
                    ("Headmaster / Headmistress", "Headmaster / Headmistress"),
                    ("Deputy Head", "Deputy Head"),
                    ("HOD", "HOD"),
                    ("Bursar / Accounts Clerk", "Bursar / Accounts Clerk"),
                    ("Accountant", "Accountant"),
                    ("Registrar / Office Clerk", "Registrar / Office Clerk"),
                    ("Clerk", "Clerk"),
                    ("Teacher", "Teacher"),
                    ("Librarian", "Librarian"),
                    ("Transport Staff", "Transport Staff"),
                    ("Hostel Staff", "Hostel Staff"),
                    ("Nurse", "Nurse"),
                    ("Parent", "Parent"),
                    ("Student", "Student"),
                ],
                default="Teacher",
                max_length=80,
            ),
        ),
    ]
