# Generated by Django 6.0.6 on 2026-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_expand_staff_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Administrator', 'Administrator'), ('Headmaster', 'Headmaster'), ('Headmaster / Headmistress', 'Headmaster / Headmistress'), ('Deputy Head', 'Deputy Head'), ('HOD', 'HOD'), ('Bursar / Accounts Clerk', 'Bursar / Accounts Clerk'), ('Accountant', 'Accountant'), ('Registrar / Office Clerk', 'Registrar / Office Clerk'), ('Clerk', 'Clerk'), ('Teacher', 'Teacher'), ('Librarian', 'Librarian'), ('Transport Staff', 'Transport Staff'), ('Hostel Staff', 'Hostel Staff'), ('Nurse', 'Nurse'), ('SaaS Administrator', 'SaaS Administrator'), ('Academic Administrator', 'Academic Administrator'), ('Finance Officer', 'Finance Officer'), ('HR Officer', 'HR Officer'), ('Payroll Officer', 'Payroll Officer'), ('Guidance Counsellor', 'Guidance Counsellor'), ('Auditor', 'Auditor'), ('Parent', 'Parent'), ('Student', 'Student')], default='Teacher', max_length=80),
        ),
    ]
