"""
URL configuration for school_system_django project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from accounts import views as account_views
from academics import views as academic_views
from attendance import views as attendance_views
from exams import views as exam_views
from fees import views as fee_views
from finance import views as finance_views
from notifications import views as notification_views
from parents import views as parent_views
from portals import views as portal_views
from reports import views as report_views
from settings_app import views as settings_views
from staff import views as staff_views
from students import views as student_views
from teachers import views as teacher_views
from website import views as website_views

from student_registry import views as registry_views
from results_centre import views as results_centre_views
from attendance_ledger import views as attendance_ledger_views
from timetable_engine import views as timetable_engine_views
from exam_coordinator import views as exam_coordinator_views
from fees_management import views as fees_management_views
from accounting_erp import views as accounting_erp_views
from subject_management import views as subject_management_views


urlpatterns = [
    path('', website_views.home, name='website'),
    path('about-us', website_views.page, {"slug": "about-us"}, name='website_about'),
    path('admissions', website_views.page, {"slug": "admissions"}, name='website_admissions'),
    path('academics', website_views.page, {"slug": "academics"}, name='website_academics'),
    path('departments', website_views.page, {"slug": "departments"}, name='website_departments'),
    path('gallery', website_views.page, {"slug": "gallery"}, name='website_gallery'),
    path('events', website_views.page, {"slug": "events"}, name='website_events'),
    path('news', website_views.page, {"slug": "news"}, name='website_news'),
    path('contact-us', website_views.page, {"slug": "contact-us"}, name='website_contact'),
    path('enquiry', website_views.enquiry, name='website_enquiry'),
    path('login', lambda request: redirect('accounts:login'), name='login_redirect'),
    path('staff/login', account_views.login_view, name='staff_login'),
    path('staff-portal', staff_views.portal, name='staff_portal'),
    path('staff-portal/profile', staff_views.portal_profile, name='staff_portal_profile'),
    path('staff-portal/api/<str:module>', staff_views.portal_api, name='staff_portal_api'),
    path('logout', account_views.logout_view, name='logout'),
    path('dashboard', account_views.dashboard, name='dashboard'),
    path('users', account_views.users, name='users'),
    path('users/new', account_views.new_user, name='new_user'),
    path('users/<int:user_id>', account_views.user_detail, name='user_detail'),
    path('users/<int:user_id>/edit', account_views.edit_user, name='edit_user'),
    path('users/<int:user_id>/delete', account_views.delete_user, name='delete_user'),
    path('audit-trail', settings_views.audit, name='audit_trail'),
    path('settings', settings_views.settings, name='settings'),
    path('settings/whatsapp/test', settings_views.settings, name='whatsapp_test_send'),
    path('guardians', parent_views.parents, name='guardians'),
    path('guardians/new', parent_views.new, name='new_guardian'),
    path('guardians/<int:guardian_id>', parent_views.detail, name='guardian_detail'),
    path('guardians/<int:guardian_id>/edit', parent_views.edit, name='edit_guardian'),
    path('guardians/<int:guardian_id>/delete', parent_views.delete, name='delete_guardian'),
    path('teachers', teacher_views.profiles, name='teachers'),
    path('teachers/new', teacher_views.new, name='new_teacher'),
    path('teachers/<int:profile_id>', teacher_views.detail, name='teacher_detail'),
    path('teachers/<int:profile_id>/edit', teacher_views.edit, name='edit_teacher'),
    path('teachers/<int:profile_id>/delete', teacher_views.delete, name='delete_teacher'),
    path('teacher-attendance', teacher_views.attendance, name='teacher_attendance'),
    path('teacher-attendance/new', teacher_views.attendance_new, name='new_teacher_attendance'),
    path('teacher-attendance/<int:attendance_id>/edit', teacher_views.attendance_edit, name='edit_teacher_attendance'),
    path('teacher-attendance/<int:attendance_id>/delete', teacher_views.attendance_delete, name='delete_teacher_attendance'),
    path('classes', academic_views.classes, name='classes'),
    path('classes/new', academic_views.class_new, name='new_class'),
    path('classes/<int:class_id>', academic_views.class_detail, name='class_detail'),
    path('classes/<int:class_id>/edit', academic_views.class_edit, name='edit_class'),
    path('classes/<int:class_id>/delete', academic_views.class_delete, name='delete_class'),
    path('subjects', academic_views.subjects, name='subjects'),
    path('subjects/new', academic_views.subject_new, name='new_subject'),
    path('subjects/<int:subject_id>', academic_views.subject_detail, name='subject_detail'),
    path('subjects/<int:subject_id>/edit', academic_views.subject_edit, name='edit_subject'),
    path('subjects/<int:subject_id>/delete', academic_views.subject_delete, name='delete_subject'),
    path('allocations', subject_management_views.allocations_list, name='allocations_list'),
    path('allocations/new', subject_management_views.allocation_new, name='new_allocation'),
    path('allocations/<int:allocation_id>/edit', subject_management_views.allocation_edit, name='edit_allocation'),
    path('allocations/<int:allocation_id>/delete', subject_management_views.allocation_delete, name='delete_allocation'),
    path('timetables', timetable_engine_views.timetable_list_view, name='timetables'),
    path('timetables/', include('timetable.urls')),
    path('attendance', attendance_views.student_attendance, name='attendance'),
    path('attendance/ledger', attendance_ledger_views.attendance_list_view, name='attendance_ledger'),
    path('attendance/register', attendance_views.class_attendance_register, name='class_attendance_register'),
    path('attendance/new', attendance_views.new, name='new_attendance'),
    path('attendance/<int:attendance_id>/edit', attendance_views.edit, name='edit_attendance'),
    path('attendance/<int:attendance_id>/delete', attendance_views.delete, name='delete_attendance'),
    path('attendance/monthly', attendance_views.monthly, name='attendance_monthly'),
    path('pupils/register', student_views.register, name='register_pupil'),
    path('pupils/transition/<int:pk>', registry_views.student_transition_view, name='transition_pupil'),
    path('pupils', student_views.records, name='pupils'),
    path('pupils/<str:admission_no>/edit', student_views.edit, name='edit_pupil_by_admission'),
    path('pupils/<str:admission_no>/delete', student_views.delete, name='delete_pupil_by_admission'),
    path('pupils/<str:admission_no>/print', student_views.detail, name='print_pupil_by_admission'),
    path('pupils/<str:admission_no>/payments', student_views.payment_history_view, name='pupil_payment_history'),
    path('pupils/<str:admission_no>/balance', student_views.balance, name='pupil_balance'),
    path('pupils/<str:admission_no>/offer-letter/pdf', student_views.offer_letter, name='pupil_offer_letter_pdf_by_admission'),
    path('pupils/<str:admission_no>/promote', student_views.promote, name='pupil_promote'),
    path('pupils/<str:admission_no>/transfer', student_views.status, {"action": "transfer"}, name='pupil_transfer_by_admission'),
    path('pupils/<str:admission_no>/deactivate', student_views.deactivate, name='pupil_deactivate'),
    path('pupils/<str:admission_no>/status/<str:action>', student_views.status, name='pupil_status_by_admission'),
    path('pupils/<str:admission_no>/transfer-letter', student_views.transfer_letter, name='pupil_transfer_letter_by_admission'),
    path('pupils/<str:admission_no>/transfer-letter/pdf', student_views.transfer_letter, name='pupil_transfer_letter_pdf_by_admission'),
    path('pupils/<str:admission_no>', student_views.detail, name='pupil_detail_by_admission'),
    path('pupils/<int:pupil_id>', student_views.detail, name='pupil_detail'),
    path('pupils/<int:pupil_id>/edit', student_views.edit, name='edit_pupil'),
    path('pupils/<int:pupil_id>/delete', student_views.delete, name='delete_pupil'),
    path('pupils/<int:pupil_id>/print', student_views.detail, name='print_pupil'),
    path('pupils/<int:pupil_id>/payments', student_views.payment_history_view, name='pupil_payment_history_by_id'),
    path('pupils/<int:pupil_id>/balance', student_views.balance, name='pupil_balance_by_id'),
    path('pupils/<int:pupil_id>/offer-letter/pdf', student_views.offer_letter, name='pupil_offer_letter_pdf'),
    path('pupils/<int:pupil_id>/promote', student_views.promote, name='pupil_promote_by_id'),
    path('pupils/<int:pupil_id>/transfer', student_views.status, {"action": "transfer"}, name='pupil_transfer'),
    path('pupils/<int:pupil_id>/deactivate', student_views.deactivate, name='pupil_deactivate_by_id'),
    path('pupils/<int:pupil_id>/status/<str:action>', student_views.status, name='pupil_status_action'),
    path('pupils/<int:pupil_id>/transfer-letter', student_views.transfer_letter, name='pupil_transfer_letter'),
    path('pupils/<int:pupil_id>/transfer-letter/pdf', student_views.transfer_letter, name='pupil_transfer_letter_pdf'),
    path('pupils/<int:pupil_id>/balance-adjustments', student_views.balance_adjustments, name='pupil_balance_adjustments'),
    path('pupils/<int:pupil_id>/balance-adjustments/new', student_views.balance_adjustment_new, name='new_pupil_balance_adjustment'),
    path('pupils/<int:pupil_id>/fee-override', student_views.fee_override, name='pupil_fee_override'),
    path('pupils/<int:pupil_id>/fee-override/new', student_views.fee_override_new, name='new_pupil_fee_override'),
    path('completed-students', student_views.completed, name='completed_students'),
    path('textbook-loans', student_views.textbooks, name='textbook_loans'),
    path('textbook-loans/new', student_views.textbook_new, name='new_textbook_loan'),
    path('textbook-loans/<int:loan_id>/edit', student_views.textbook_edit, name='edit_textbook_loan'),
    path('textbook-loans/<int:loan_id>/delete', student_views.textbook_delete, name='delete_textbook_loan'),
    path('textbook-loans/<int:loan_id>/return', student_views.textbook_return, name='return_textbook_loan'),
    path('exams', exam_coordinator_views.exam_list_view, name='exams'),
    path('exams/new', exam_views.exam_new, name='new_exam'),
    path('exams/<int:exam_id>', exam_views.exam_detail, name='exam_detail'),
    path('exams/<int:exam_id>/edit', exam_views.exam_edit, name='edit_exam'),
    path('exams/<int:exam_id>/delete', exam_views.exam_delete, name='delete_exam'),
    path('results', exam_views.results, name='results'),
    path('results/centre', results_centre_views.result_list_view, name='results_centre'),
    path('results/new', exam_views.result_new, name='new_result'),
    path('results/class-entry', exam_views.result_class_entry, name='result_class_entry'),
    path('results/bulk-publish', exam_views.result_bulk_publish, name='result_bulk_publish'),
    path('results/publish-all-pending', exam_views.publish_all_pending, name='publish_all_pending'),
    path('results/schedule/pdf', exam_views.result_mark_schedule_pdf, name='result_mark_schedule_pdf'),
    path('results/export/pdf', exam_views.results_export_pdf, name='results_export_pdf'),
    path('results/verify/<int:result_id>/', exam_views.results_verify, name='results_verify_slash'),
    path('results/<int:result_id>/', exam_views.result_detail, name='result_detail_slash'),
    path('results/<int:result_id>/pdf/', exam_views.result_detail, name='result_detail_pdf_slash'),
    path('results/<int:result_id>/edit/', exam_views.result_edit, name='edit_result_slash'),
    path('results/<int:result_id>/delete/', exam_views.result_delete, name='delete_result_slash'),
    path('results/<int:result_id>/publish/', exam_views.result_publish, name='publish_result_slash'),
    path('results/<int:result_id>', exam_views.result_detail, name='result_detail'),
    path('results/<int:result_id>/pdf', exam_views.result_detail, name='result_detail_pdf'),
    path('results/<int:result_id>/edit', exam_views.result_edit, name='edit_result'),
    path('results/<int:result_id>/delete', exam_views.result_delete, name='delete_result'),
    path('results/<int:result_id>/publish', exam_views.result_publish, name='publish_result'),
    path('results/verify/<int:result_id>', exam_views.results_verify, name='results_verify'),
    path('results/slip', exam_views.results, name='result_slip'),
    path('results/slip/pdf', exam_views.results, name='result_slip_pdf'),
    path('results/slip/whatsapp', exam_views.results, name='result_slip_whatsapp'),
    path('performance-predictions', exam_views.predictions, name='performance_predictions'),
    path('e-learning', academic_views.e_learning, name='e_learning'),
    path('e-learning/new', academic_views.e_learning_new, name='new_e_learning'),
    path('e-learning/<int:assignment_id>', academic_views.e_learning_detail, name='e_learning_detail'),
    path('e-learning/<int:assignment_id>/edit', academic_views.e_learning_edit, name='edit_e_learning'),
    path('e-learning/<int:assignment_id>/delete', academic_views.e_learning_delete, name='delete_e_learning'),
    path('e-learning/submissions/<int:submission_id>/mark', academic_views.mark_submission, name='mark_e_learning_submission'),
    path('e-learning/download/<str:file_type>/<int:item_id>', academic_views.download, name='e_learning_download'),
    path('notifications/', include('notifications.urls')),
    path('notifications', notification_views.notifications, name='notifications'),
    path('notifications/<int:communication_id>', notification_views.detail, name='notification_detail'),
    path('fees-structure', fees_management_views.fee_account_list_view, name='fees_structure'),
    path('reports/accounting', accounting_erp_views.chart_of_accounts_view, name='accounting_reports'),
    path('fees-structure/generate-bills', fee_views.generate_term_bills, name='generate_term_bills'),
    path('fees-structure/new', fee_views.structure_new, name='new_fees_structure'),
    path('fees-structure/<int:fee_id>', fee_views.structure_detail, name='fees_structure_detail'),
    path('fees-structure/<int:fee_id>/edit', fee_views.structure_edit, name='edit_fees_structure'),
    path('fees-structure/<int:fee_id>/delete', fee_views.structure_delete, name='delete_fees_structure'),
    path('payments', fee_views.payments, name='payments'),
    path('payments/new', fee_views.record_payment, name='record_payment'),
    path('payments/<str:receipt_no>/edit', fee_views.payment_edit, name='edit_payment_by_receipt'),
    path('payments/<str:receipt_no>/delete', fee_views.payment_delete, name='delete_payment_by_receipt'),
    path('payments/<int:payment_id>/edit', fee_views.payment_edit, name='edit_payment'),
    path('payments/<int:payment_id>/delete', fee_views.payment_delete, name='delete_payment'),
    path('receipt/<str:receipt_no>/pdf', fee_views.receipt, name='receipt_pdf_by_number'),
    path('receipt/<str:receipt_no>', fee_views.receipt, name='receipt_by_number'),
    path('receipt/<int:payment_id>', fee_views.receipt, name='receipt'),
    path('receipt/<int:payment_id>/pdf', fee_views.receipt, name='receipt_pdf'),
    path('receipt/<int:payment_id>/whatsapp', fee_views.receipt, name='receipt_whatsapp'),
    path('portal-payment-requests', fee_views.portal_requests, name='portal_payment_requests'),
    path('portal-payment-requests/<int:request_id>', fee_views.portal_request_detail, name='portal_payment_request_detail'),
    path('portal-payment-requests/<int:request_id>/edit', fee_views.portal_request_edit, name='portal_payment_request_edit'),
    path('portal-payment-requests/<int:request_id>/delete', fee_views.portal_request_delete, name='portal_payment_request_delete'),
    path('portal-payment-requests/<int:request_id>/<str:action>', fee_views.portal_request_action, name='portal_payment_request_action'),
    path('master-receipts', finance_views.master_receipts, name='master_receipts'),
    path('master-receipts/new', finance_views.master_receipt_new, name='new_master_receipt'),
    path('master-receipts/<int:master_receipt_id>', finance_views.master_receipt_detail, name='master_receipt_detail'),
    path('master-receipts/<int:master_receipt_id>/pdf', finance_views.master_receipt_detail, name='master_receipt_pdf'),
    path('expenses', finance_views.expenses, name='expenses'),
    path('expenses/new', finance_views.record_expense, name='record_expense'),
    path('expenses/<int:expense_id>', finance_views.expense_detail, name='expense_detail'),
    path('expenses/<int:expense_id>/edit', finance_views.expense_edit, name='edit_expense'),
    path('expenses/<int:expense_id>/delete', finance_views.expense_delete, name='delete_expense'),
    path('reports', report_views.reports, name='reports'),
    path('reports/pdf', report_views.reports, name='reports_pdf'),
    path('reports/statement', report_views.statement, name='statement'),
    path('reports/statement/pdf', report_views.statement, name='statement_pdf'),
    path('library', academic_views.library, name='library'),
    path('library/new', academic_views.library_new, name='new_library_book'),
    path('library/<int:book_id>/edit', academic_views.library_edit, name='edit_library_book'),
    path('library/<int:book_id>/delete', academic_views.library_delete, name='delete_library_book'),
    path('library/<int:issue_id>/return', academic_views.return_library_book, name='return_library_book'),
    path('inventory', finance_views.inventory, name='inventory'),
    path('inventory/new', finance_views.inventory_new, name='new_inventory_item'),
    path('inventory/<int:item_id>', finance_views.inventory_detail, name='inventory_item_detail'),
    path('inventory/<int:item_id>/edit', finance_views.inventory_edit, name='edit_inventory_item'),
    path('inventory/<int:item_id>/add-stock', finance_views.inventory_add_stock, name='inventory_add_stock'),
    path('inventory/<int:item_id>/delete', finance_views.inventory_delete, name='delete_inventory_item'),
    path('uniform-pos', finance_views.pos, name='uniform_pos'),
    path('uniform-pos/new', finance_views.pos_new, name='new_pos_sale'),
    path('uniform-pos/<int:sale_id>/edit', finance_views.pos_edit, name='edit_pos_sale'),
    path('uniform-pos/receipt/<int:sale_id>', finance_views.pos_receipt, name='pos_receipt'),
    path('uniform-pos/receipt/<int:sale_id>/pdf', finance_views.pos_receipt, name='pos_receipt_pdf'),
    path('backups', settings_views.backups, name='database_backups'),
    path('backups/create', settings_views.create_backup, name='create_database_backup'),
    path('backups/<int:backup_id>/download', settings_views.download_backup, name='download_database_backup'),
    path('offline-sync', settings_views.offline_sync, name='offline_sync'),
    path('offline-sync/<int:event_id>/retry', settings_views.retry_sync, name='retry_offline_sync'),
    path('student-portal/login', portal_views.student_login, name='portal_login'),
    path('student-portal/logout', portal_views.student_logout, name='portal_logout'),
    path('student-portal', portal_views.student, name='portal_dashboard'),
    path('student-portal/profile', portal_views.student_profile, name='portal_profile'),
    path('student-portal/attendance', portal_views.student_attendance, name='portal_attendance'),
    path('student-portal/pay', portal_views.student_pay, name='portal_pay_fees'),
    path('student-portal/statement', portal_views.student_statement, name='portal_statement'),
    path('student-portal/statement/pdf', portal_views.student_statement, name='portal_statement_pdf'),
    path('student-portal/textbooks', portal_views.student_textbooks, name='portal_textbooks'),
    path('student-portal/timetable', portal_views.student_timetable, name='portal_timetable'),
    path('student-portal/e-learning', portal_views.student_e_learning, name='portal_e_learning'),
    path('student-portal/e-learning/submit/<int:assignment_id>', portal_views.student_submit_assignment, name='portal_submit_assignment'),
    path('student-portal/results', portal_views.student_results, name='portal_results'),
    path('student-portal/results/pdf', portal_views.student_results, name='portal_results_pdf'),
    path('student-portal/api/updates', portal_views.student_updates, name='portal_update_events'),
    path('student-portal/api/<str:module>', portal_views.student_api, name='portal_module_api'),
    path('student-portal/receipt/<str:receipt_no>', portal_views.student_receipt, name='portal_receipt_by_number'),
    path('student-portal/receipt/<str:receipt_no>/pdf', portal_views.student_receipt, name='portal_receipt_pdf_by_number'),
    path('student-portal/receipt/<int:payment_id>', portal_views.student_receipt, name='portal_receipt'),
    path('student-portal/receipt/<int:payment_id>/pdf', portal_views.student_receipt, name='portal_receipt_pdf'),
    path('student-portal/payment/<str:reference_no>', portal_views.student_pay, name='portal_payment_status'),
    path('student-portal/payment/<str:reference_no>/poll', portal_views.student_pay, name='portal_payment_poll'),
    path('student-portal/payment/<str:reference_no>/return', portal_views.student_pay, name='portal_payment_return'),
    path('paynow/result/<str:reference_no>', portal_views.student_pay, name='portal_payment_result'),
    path('api/pupil-balance', fee_views.pupil_balance, name='api_pupil_balance'),
    path('api/pupil-search', fee_views.pupil_search, name='api_pupil_search'),
    path('api/result-pupil-search', exam_views.result_pupil_search, name='api_result_pupil_search'),
    path('service-worker.js', lambda request: redirect('/static/service-worker.js'), name='service_worker'),
    path('payroll/', include('payroll.urls')),
    path('django/students/', include('students.urls')),
    path('django/parents/', include('parents.urls')),
    path('django/staff/', include('staff.urls')),
    path('django/teachers/', include('teachers.urls')),
    path('django/academics/', include('academics.urls')),
    path('django/attendance/', include('attendance.urls')),
    path('django/exams/', include('exams.urls')),
    path('django/examinations/', include('examinations.urls')),
    path('django/fees/', include('fees.urls')),
    path('django/finance/', include('finance.urls')),
    path('django/reports/', include('reports.urls')),
    path('django/settings/', include('settings_app.urls')),
    path('django/website/', include('website.urls')),
    path('django/notifications/', include(('notifications.urls', 'notifications'), namespace='django_notifications')),
    path('django/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
