# Generated by Django 6.0.6 on 2026-07-10 07:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('default_points', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major')], default='Minor', max_length=20)),
            ],
            options={
                'db_table': 'discipline_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BehaviourImprovementPlan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('review_date', models.DateField()),
                ('targets', models.TextField()),
                ('activities', models.TextField()),
                ('progress_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Discontinued', 'Discontinued')], default='In Progress', max_length=30)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_plans', to='human_resources.employeeprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_plans', to='student_registry.student')),
            ],
            options={
                'db_table': 'behaviour_improvement_plans',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryIncident',
            fields=[
                ('incident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incident_no', models.CharField(max_length=50, unique=True)),
                ('incident_date', models.DateField(default=datetime.date.today)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('severity', models.CharField(default='Minor', max_length=20)),
                ('description', models.TextField()),
                ('witnesses', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Under Investigation', 'Under Investigation'), ('Pending Action', 'Pending Action'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Appealed', 'Appealed')], default='Under Investigation', max_length=30)),
                ('hostel_incident', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='human_resources.employeeprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_incidents', to='student_registry.student')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='discipline.disciplinecategory')),
            ],
            options={
                'db_table': 'disciplinary_incidents',
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour_score', models.IntegerField(default=100)),
                ('active_sanctions', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('counselling_referrals', models.IntegerField(default=0)),
                ('parent_meetings', models.IntegerField(default=0)),
                ('suspension_history', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_profile', to='student_registry.student')),
            ],
            options={
                'db_table': 'discipline_profiles',
            },
        ),
        migrations.CreateModel(
            name='DisciplineSanction',
            fields=[
                ('sanction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sanction_type', models.CharField(choices=[('Verbal Warning', 'Verbal Warning'), ('Written Warning', 'Written Warning'), ('Community Service', 'Community Service'), ('Detention', 'Detention'), ('Suspension', 'Suspension'), ('Expulsion Recommendation', 'Expulsion Recommendation'), ('Parent Meeting', 'Parent Meeting'), ('Counselling Referral', 'Counselling Referral')], max_length=40)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sanctions', to='human_resources.employeeprofile')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='discipline.disciplinaryincident')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_sanctions', to='student_registry.student')),
            ],
            options={
                'db_table': 'discipline_sanctions',
            },
        ),
        migrations.CreateModel(
            name='DisciplineSuspension',
            fields=[
                ('suspension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suspension_type', models.CharField(choices=[('In-School', 'In-School Suspension'), ('External', 'External Suspension'), ('Indefinite', 'Indefinite Suspension')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('sanction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='discipline.disciplinesanction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_suspensions', to='student_registry.student')),
            ],
            options={
                'db_table': 'discipline_suspensions',
            },
        ),
        migrations.CreateModel(
            name='ParentMeeting',
            fields=[
                ('meeting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('participants', models.TextField(help_text='Names of parents, teachers, and administrators attending')),
                ('minutes', models.TextField()),
                ('outcomes', models.TextField()),
                ('follow_up_actions', models.TextField(blank=True, null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='discipline.disciplinaryincident')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_meetings', to='student_registry.student')),
            ],
            options={
                'db_table': 'discipline_parent_meetings',
            },
        ),
    ]
