# Generated by Django 6.0.6 on 2026-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=180)),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=80, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
                ('end_date', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Planned', max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'exam_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grade', models.CharField(max_length=20)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'result_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('pupil_id', models.IntegerField()),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('status', models.CharField(default='Draft', max_length=40)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_mark', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('published_at', models.TextField(blank=True, null=True)),
                ('published_by', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('grade_snapshot', models.CharField(blank=True, max_length=80, null=True)),
                ('class_stream_snapshot', models.CharField(blank=True, max_length=80, null=True)),
                ('class_position', models.IntegerField(blank=True, null=True)),
                ('grade_position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result_sheets',
                'managed': False,
            },
        ),
    ]
