# Generated by Django 6.0.6 on 2026-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendanceRecord',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('attendance_date', models.TextField()),
                ('status', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('marked_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'teacher_attendance_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('assigned_subjects', models.TextField(blank=True, null=True)),
                ('workload_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'teacher_profiles',
                'managed': False,
            },
        ),
    ]
