# Generated by Django 6.0.6 on 2026-07-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_leavetype_applicant_cv_applicant_interview_score_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_profile_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('teaching_subjects', models.TextField(blank=True, null=True)),
                ('assigned_forms', models.TextField(blank=True, null=True)),
                ('assigned_classes', models.TextField(blank=True, null=True)),
                ('workload_notes', models.TextField(blank=True, null=True)),
                ('professional_registration', models.CharField(blank=True, max_length=120, null=True)),
                ('teaching_experience_years', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('class_teacher_assignment', models.CharField(blank=True, max_length=120, null=True)),
                ('head_of_department_assignment', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_extension', to='human_resources.employeeprofile')),
            ],
            options={
                'db_table': 'teacher_employee_profiles',
                'ordering': ['employee__surname', 'employee__first_name'],
            },
        ),
    ]
