# Generated by Django 6.0.6 on 2026-07-03 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('O_LEVEL', 'Ordinary Level (O-Level)'), ('A_LEVEL', 'Advanced Level (A-Level)')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subject_catalog',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectManagementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('detail', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_mgmt_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='student_registry.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='subject_management.subject')),
            ],
            options={
                'db_table': 'student_subject_registrations',
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject', 'academic_year', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.academicyear')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.form')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='subject_management.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_subject_allocations',
                'ordering': ['teacher', 'subject', 'form', 'stream'],
                'unique_together': {('teacher', 'subject', 'academic_year', 'academic_term', 'form', 'stream')},
            },
        ),
    ]
