# Generated by Django 6.0.6 on 2026-07-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_management', '0002_seed_baseline_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Sciences', 'Sciences'), ('Commercials', 'Commercials'), ('Humanities', 'Humanities'), ('Practicals', 'Practicals')], default='Languages', max_length=50),
        ),
    ]
