# Generated by Django 6.0.6 on 2026-07-05 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0001_initial'),
        ('subject_management', '0003_subject_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teachersubjectallocation',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'academic_year', 'academic_term', 'form', 'stream'), name='unique_teacher_subject_allocation_constraint'),
        ),
    ]
