# Generated by Django 6.0.6 on 2026-07-05 08:34

import saas_tenant_management.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTenant',
            fields=[
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='RAYDON HIGH SCHOOL', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('local_testing_port', models.IntegerField(blank=True, null=True, unique=True)),
                ('production_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=saas_tenant_management.models.tenant_media_path)),
                ('address', models.TextField(default='Harare, Zimbabwe')),
                ('telephone', models.CharField(default='+263771000000', max_length=50)),
                ('subscription_plan', models.CharField(choices=[('BASIC', 'Basic School Plan'), ('PREMIUM', 'Premium Enterprise Plan'), ('ELITE', 'Elite Unified Plan')], default='BASIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Tenant',
                'verbose_name_plural': 'School Tenants',
                'db_table': 'saas_school_tenants',
            },
        ),
    ]
