# Generated by Django 6.0.6 on 2026-07-10 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_tenant_management', '0002_portal_runtime_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='OPEN', max_length=30)),
            ],
            options={
                'db_table': 'saas_subscription_invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('STARTER', 'Starter Package'), ('STANDARD', 'Standard Package'), ('ENTERPRISE', 'Enterprise Package'), ('CUSTOM', 'Custom Package'), ('BASIC', 'Basic School Plan'), ('PREMIUM', 'Premium Enterprise Plan'), ('ELITE', 'Elite Unified Plan')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quarterly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'saas_subscription_plans',
                'ordering': ['monthly_price', 'name'],
            },
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='colour_theme',
            field=models.CharField(default='#0f766e', max_length=30),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='electronic_stamp',
            field=models.CharField(default='Electronic School Stamp', max_length=120),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='ministry_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='registration_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='report_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='school_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='school_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='tenant_database_identifier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schooltenant',
            name='subscription_plan',
            field=models.CharField(choices=[('STARTER', 'Starter Package'), ('STANDARD', 'Standard Package'), ('ENTERPRISE', 'Enterprise Package'), ('CUSTOM', 'Custom Package'), ('BASIC', 'Basic School Plan'), ('PREMIUM', 'Premium Enterprise Plan'), ('ELITE', 'Elite Unified Plan')], default='BASIC', max_length=20),
        ),
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('compulsory', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dependencies', models.ManyToManyField(blank=True, to='saas_tenant_management.moduledefinition')),
            ],
            options={
                'db_table': 'saas_module_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaaSAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_audit_logs', to='saas_tenant_management.schooltenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saas_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolBrandingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_header', models.CharField(blank=True, max_length=255, null=True)),
                ('electronic_stamp', models.CharField(default='Electronic School Stamp', max_length=120)),
                ('pdf_branding_notes', models.TextField(blank=True, null=True)),
                ('colour_theme', models.CharField(default='#0f766e', max_length=30)),
                ('white_label_enabled', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding_profile', to='saas_tenant_management.schooltenant')),
            ],
            options={
                'db_table': 'saas_school_branding_profiles',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('ONLINE', 'Online Payment')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='saas_tenant_management.subscriptioninvoice')),
            ],
            options={
                'db_table': 'saas_subscription_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='saas_tenant_management.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='saas_tenant_management.schooltenant')),
            ],
            options={
                'db_table': 'saas_tenant_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='saas_tenant_management.tenantsubscription'),
        ),
        migrations.CreateModel(
            name='TenantModuleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('TRIAL', 'Trial'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_activations', to='saas_tenant_management.moduledefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activations', to='saas_tenant_management.schooltenant')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_activations', to='saas_tenant_management.tenantsubscription')),
            ],
            options={
                'db_table': 'saas_tenant_module_activations',
                'unique_together': {('tenant', 'module')},
            },
        ),
        migrations.CreateModel(
            name='TenantUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('storage_usage_mb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('database_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_module_count', models.PositiveIntegerField(default=0)),
                ('api_usage_count', models.PositiveIntegerField(default=0)),
                ('login_activity_count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='saas_tenant_management.schooltenant')),
            ],
            options={
                'db_table': 'saas_tenant_usage_snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('tenant', 'snapshot_date')},
            },
        ),
    ]
