# Generated by Django 6.0 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas_tenant_management", "0003_subscriptioninvoice_subscriptionplan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("saas_tenant_management.schooltenant",),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="database_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="database_password",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="database_user",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="is_trial",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="max_students",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="max_users",
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter"),
                    ("STANDARD", "Standard"),
                    ("PREMIUM", "Premium"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="subdomain",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="subscription_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="subscription_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schooltenant",
            name="trial_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="next_billing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TenantModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module_name", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_modules",
                        to="saas_tenant_management.schooltenant",
                    ),
                ),
            ],
            options={
                "db_table": "saas_tenant_modules",
                "ordering": ["module_name"],
                "unique_together": {("tenant", "module_name")},
            },
        ),
    ]
