# Generated by Django 6.0.6 on 2026-07-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
        ('subject_management', '0003_subject_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZIMSECCandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A*', 'A* (Distinction)'), ('A', 'A (Distinction)'), ('B', 'B (Credit)'), ('C', 'C (Pass)'), ('D', 'D (Below Pass)'), ('E', 'E (Below Pass - A-Level Only)'), ('U', 'U (Ungraded)')], max_length=5)),
                ('session', models.CharField(choices=[('JUNE', 'June Examination Session'), ('NOVEMBER', 'November Examination Session')], max_length=20)),
                ('exam_year', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zimsec_results', to='student_registry.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zimsec_results', to='subject_management.subject')),
            ],
            options={
                'db_table': 'zimsec_candidate_results',
                'ordering': ['-exam_year', 'student', 'subject'],
                'unique_together': {('student', 'subject', 'exam_year')},
            },
        ),
    ]
