# Generated by Django 6.0.6 on 2026-07-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_level', models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], max_length=20)),
            ],
            options={
                'db_table': 'registry_fee_structures',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic_structure.academicclass')),
            ],
            options={
                'db_table': 'registry_students',
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('relationship', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='student_registry.student')),
            ],
            options={
                'db_table': 'registry_guardians',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='student_registry.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='student_registry.student')),
            ],
            options={
                'db_table': 'registry_student_fee_records',
                'unique_together': {('student', 'fee_structure')},
            },
        ),
    ]
