# Generated by Django 6.0.6 on 2026-06-11 04:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=120)),
                ('department', models.CharField(default='School', max_length=120)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(choices=[('Bank transfer', 'Bank transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('EcoCash', 'EcoCash')], default='Bank transfer', max_length=30)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('On leave', 'On leave'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'permissions': [('can_process_payroll', 'Can process payroll'), ('can_approve_payroll', 'Can approve payroll'), ('can_export_payroll', 'Can export payroll')],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=180)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=180)),
                ('employee_number', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('payment_method', models.CharField(choices=[('Bank transfer', 'Bank transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('EcoCash', 'EcoCash')], max_length=30)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('nssa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unpaid_leave', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_runs', to='payroll.payrollrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='payroll.employeepayrollprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='payroll.payrollperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('source', models.CharField(default='run', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['item_type', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('profile_created', 'Profile created'), ('profile_updated', 'Profile updated'), ('period_processed', 'Period processed'), ('run_updated', 'Run updated'), ('status_changed', 'Status changed'), ('exported', 'Exported'), ('payslip_generated', 'Payslip generated')], max_length=60)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollperiod')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['adjustment_type', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(max_length=80, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['period', 'department'], name='payroll_pay_period__40384d_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['employee_number'], name='payroll_pay_employe_eb2a7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('period', 'employee_profile')},
        ),
    ]
