# Generated by Django 6.0.6 on 2026-07-09 15:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollComponentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('component_type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction'), ('STATUTORY', 'Statutory Deduction')], max_length=20)),
                ('taxable', models.BooleanField(default=True)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('percentage_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('formula', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['component_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('expression', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('responsibility_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='hr_employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_profile', to='human_resources.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='medical_aid_scheme',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='pension_scheme',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='tax_status',
            field=models.CharField(default='Taxable', max_length=80),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('FORTNIGHT', 'Fortnight')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='account_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='medical_aid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='savings_scheme',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='union_subscription',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='electronic_stamp',
            field=models.CharField(default='Electronic School Stamp', max_length=120),
        ),
        migrations.AddField(
            model_name='payslip',
            name='qr_code_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payrollauditlog',
            name='action',
            field=models.CharField(choices=[('profile_created', 'Profile created'), ('profile_updated', 'Profile updated'), ('period_processed', 'Period processed'), ('run_updated', 'Run updated'), ('status_changed', 'Status changed'), ('exported', 'Exported'), ('payslip_generated', 'Payslip generated'), ('loan_created', 'Loan created'), ('loan_deducted', 'Loan deducted'), ('payroll_posted', 'Payroll posted'), ('bank_file_generated', 'Bank file generated')], max_length=60),
        ),
        migrations.CreateModel(
            name='BankTransferFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=180)),
                ('file_format', models.CharField(default='Excel', max_length=30)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_files', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=180)),
                ('employee_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bank_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.banktransferfile')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type', models.CharField(choices=[('HOURLY', 'Hourly Overtime'), ('DAILY', 'Daily Overtime'), ('WEEKEND', 'Weekend Overtime'), ('PUBLIC_HOLIDAY', 'Public Holiday Overtime')], max_length=30)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records', to='payroll.employeepayrollprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['period', 'employee_profile'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAccountingPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_number', models.CharField(max_length=80, unique=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_posting', to='payroll.payrollperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=50, unique=True)),
                ('loan_type', models.CharField(choices=[('STAFF_LOAN', 'Staff Loan'), ('SALARY_ADVANCE', 'Salary Advance'), ('EMERGENCY_LOAN', 'Emergency Loan')], max_length=30)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('repayment_period', models.PositiveIntegerField()),
                ('monthly_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='payroll.employeepayrollprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
