# Generated by Django 6.0.6 on 2026-07-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority')], default='MEDIUM', max_length=20)),
                ('read_receipt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Delivery'), ('SENT', 'Delivered Successfully'), ('FAILED', 'Delivery Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('old_values_json', models.JSONField(blank=True, null=True)),
                ('new_values_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_audit_ledger',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountPortalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_role', models.CharField(choices=[('PARENT', 'Parent Portal'), ('STUDENT', 'Student Portal')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_mappings', to='student_registry.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_portal_mappings',
                'unique_together': {('user', 'student', 'portal_role')},
            },
        ),
    ]
