# Generated by Django 6.0.6 on 2026-06-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_staff_admission_no'),
        ('students', '0002_textbook_loan_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=80, unique=True)),
                ('room_type', models.CharField(choices=[('Classroom', 'Normal Classroom'), ('Science Lab', 'Science Lab'), ('Computer Lab', 'Computer Lab'), ('Library', 'Library'), ('Special Room', 'Special Room')], default='Classroom', max_length=50)),
                ('capacity', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='TimetablePeriodConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_no', models.IntegerField(unique=True)),
                ('period_type', models.CharField(choices=[('Lesson', 'Lesson Period'), ('Break', 'Tea/Short Break'), ('Lunch', 'Lunch Break')], default='Lesson', max_length=50)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g. Break, Lunch, Period 1', max_length=50, null=True)),
            ],
            options={
                'ordering': ['period_no'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_periods_per_day', models.IntegerField(default=6)),
                ('max_periods_per_week', models.IntegerField(default=30)),
                ('available_days', models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text='Comma-separated day names', max_length=100)),
                ('available_periods', models.CharField(default='1,2,3,4,5,6,7,8', help_text='Comma-separated period numbers', max_length=100)),
                ('teacher', models.OneToOneField(db_column='teacher_id', limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('periods_per_week', models.IntegerField(default=4)),
                ('preferred_days', models.CharField(blank=True, help_text="Comma-separated day names e.g., 'Monday, Wednesday'", max_length=100, null=True)),
                ('preferred_sessions', models.CharField(choices=[('Morning', 'Morning Session'), ('Afternoon', 'Afternoon Session'), ('Any', 'Any Session')], default='Any', max_length=50)),
                ('is_practical', models.BooleanField(default=False, help_text='Practical subjects allow consecutive double periods')),
                ('required_room_type', models.CharField(choices=[('Classroom', 'Normal Classroom'), ('Science Lab', 'Science Lab'), ('Computer Lab', 'Computer Lab'), ('Library', 'Library'), ('Special Room', 'Special Room')], default='Classroom', max_length=50)),
                ('school_class', models.ForeignKey(db_column='class_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='students.schoolclass')),
                ('subject', models.ForeignKey(db_column='subject_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.subject')),
                ('teacher', models.ForeignKey(db_column='teacher_id', limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
