# Generated by Django 6.0.6 on 2026-07-03 18:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused'), ('Sick', 'Sick'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended')], max_length=20)),
                ('mode', models.CharField(choices=[('DAILY', 'Daily Attendance'), ('LESSON', 'Lesson/Period Attendance')], max_length=10)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='timetable.timetableperiodconfig')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student_registry.student')),
            ],
            options={
                'db_table': 'attendance_ledger_records',
                'ordering': ['-date', 'student', 'period'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='student_registry.student')),
            ],
            options={
                'verbose_name_plural': 'Student Attendance Summaries',
                'db_table': 'attendance_ledger_summaries',
            },
        ),
    ]
