import re
import sqlite3
from hashlib import sha1
from pathlib import Path

from django.apps import apps
from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction


SAFE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
INTERNAL_PREFIXES = ("sqlite_",)
POSTGRES_IDENTIFIER_LIMIT = 63

COMMON_LEGACY_INDEXES = (
    ("users", "idx_users_username", ("username",), False),
    ("users", "idx_users_admission_no", ("admission_no",), False),
    ("pupils", "idx_pupils_admission_no", ("admission_no",), False),
    ("pupils", "idx_pupils_status_class_id", ("status", "class_id"), False),
    ("pupils", "idx_pupils_status_grade_stream", ("status", "grade_id", "class_stream"), False),
    ("guardians", "idx_guardians_student_primary", ("student_id", "is_primary"), False),
    ("teacher_profiles", "idx_teacher_profiles_user_id", ("user_id",), False),
    ("teacher_profiles", "idx_teacher_profiles_email", ("email",), False),
    ("attendance_records", "idx_attendance_records_pupil_date", ("pupil_id", "attendance_date"), False),
    ("attendance_records", "idx_attendance_records_class_date", ("class_id", "attendance_date"), False),
    ("student_subjects", "idx_student_subjects_lookup", ("pupil_id", "subject_id", "academic_year"), False),
    ("result_sheets", "idx_result_sheets_pupil_term_year", ("pupil_id", "term", "year"), False),
    ("payments", "idx_payments_pupil_date", ("pupil_id", "payment_date"), False),
    ("term_bills", "idx_term_bills_pupil_term_year", ("pupil_id", "term", "year"), False),
)


def quote_name(name):
    if not SAFE_IDENTIFIER.match(name):
        raise CommandError(f"Unsafe database identifier: {name!r}")
    return connection.ops.quote_name(name)


def postgres_identifier(name):
    if not SAFE_IDENTIFIER.match(name):
        raise CommandError(f"Unsafe database identifier: {name!r}")
    if len(name) <= POSTGRES_IDENTIFIER_LIMIT:
        return name
    digest = sha1(name.encode("utf-8")).hexdigest()[:10]
    return f"{name[:POSTGRES_IDENTIFIER_LIMIT - 11]}_{digest}"


def sqlite_tables(sqlite_cursor):
    sqlite_cursor.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
        ORDER BY name
        """
    )
    return {
        row[0]
        for row in sqlite_cursor.fetchall()
        if not row[0].startswith(INTERNAL_PREFIXES)
    }


def unmanaged_model_tables():
    tables = set()
    for model in apps.get_models(include_auto_created=False):
        if not model._meta.managed:
            tables.add(model._meta.db_table)
    return tables


def sqlite_columns(sqlite_cursor, table_name):
    sqlite_cursor.execute(f"PRAGMA table_info({quote_sqlite_identifier(table_name)})")
    columns = []
    for row in sqlite_cursor.fetchall():
        columns.append(
            {
                "name": row[1],
                "type": row[2] or "",
                "notnull": bool(row[3]),
                "default": row[4],
                "pk": int(row[5] or 0),
            }
        )
    return columns


def quote_sqlite_identifier(name):
    if not SAFE_IDENTIFIER.match(name):
        raise CommandError(f"Unsafe SQLite identifier: {name!r}")
    return '"' + name.replace('"', '""') + '"'


def postgres_type(sqlite_type, is_primary_key=False):
    normalized = sqlite_type.upper()
    if "INT" in normalized:
        if is_primary_key:
            return "integer GENERATED BY DEFAULT AS IDENTITY"
        return "integer"
    if any(token in normalized for token in ("REAL", "FLOA", "DOUB")):
        return "double precision"
    if any(token in normalized for token in ("DEC", "NUM")):
        return "numeric"
    if "BLOB" in normalized:
        return "bytea"
    return "text"


def table_exists(table_name):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = %s
            """,
            [table_name],
        )
        return cursor.fetchone() is not None


def postgres_columns(table_name):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = %s
            """,
            [table_name],
        )
        return {row[0] for row in cursor.fetchall()}


def sqlite_indexes(sqlite_cursor, table_name):
    sqlite_cursor.execute(f"PRAGMA index_list({quote_sqlite_identifier(table_name)})")
    for row in sqlite_cursor.fetchall():
        index_name = row[1]
        is_unique = bool(row[2])
        origin = row[3] if len(row) > 3 else ""
        is_partial = bool(row[4]) if len(row) > 4 else False
        if index_name.startswith("sqlite_autoindex") or origin == "pk" or is_partial:
            continue
        if not SAFE_IDENTIFIER.match(index_name):
            continue
        sqlite_cursor.execute(f"PRAGMA index_info({quote_sqlite_identifier(index_name)})")
        columns = [info_row[2] for info_row in sqlite_cursor.fetchall()]
        if columns and all(SAFE_IDENTIFIER.match(column) for column in columns):
            yield index_name, columns, is_unique


def create_postgres_index(table_name, index_name, columns, unique=False):
    existing_columns = postgres_columns(table_name)
    if not set(columns).issubset(existing_columns):
        return False
    index_name = postgres_identifier(index_name)
    unique_sql = "UNIQUE " if unique else ""
    quoted_columns = ", ".join(quote_name(column) for column in columns)
    with connection.cursor() as cursor:
        cursor.execute(
            f"CREATE {unique_sql}INDEX IF NOT EXISTS {quote_name(index_name)} "
            f"ON {quote_name(table_name)} ({quoted_columns})"
        )
    return True


def create_sqlite_indexes(sqlite_cursor, table_name):
    created = 0
    for index_name, columns, is_unique in sqlite_indexes(sqlite_cursor, table_name):
        if create_postgres_index(table_name, index_name, columns, is_unique):
            created += 1
    return created


def create_common_legacy_indexes(imported_tables):
    created = 0
    existing_tables = {table for table in imported_tables if table_exists(table)}
    for table_name, index_name, columns, is_unique in COMMON_LEGACY_INDEXES:
        if table_name in existing_tables and create_postgres_index(table_name, index_name, columns, is_unique):
            created += 1
    return created


def create_or_extend_table(table_name, columns):
    if not columns:
        return

    pk_columns = [column["name"] for column in columns if column["pk"]]
    with connection.cursor() as cursor:
        if not table_exists(table_name):
            definitions = []
            for column in columns:
                definition = f"{quote_name(column['name'])} {postgres_type(column['type'], bool(column['pk']))}"
                if column["notnull"] and not column["pk"]:
                    definition += " NOT NULL"
                definitions.append(definition)
            if pk_columns:
                pk_names = ", ".join(quote_name(name) for name in pk_columns)
                definitions.append(f"PRIMARY KEY ({pk_names})")
            cursor.execute(f"CREATE TABLE {quote_name(table_name)} ({', '.join(definitions)})")
            return

        existing_columns = postgres_columns(table_name)
        for column in columns:
            if column["name"] in existing_columns:
                continue
            cursor.execute(
                f"ALTER TABLE {quote_name(table_name)} "
                f"ADD COLUMN {quote_name(column['name'])} {postgres_type(column['type'], bool(column['pk']))}"
            )


def reset_table(table_name):
    with connection.cursor() as cursor:
        cursor.execute(f"TRUNCATE TABLE {quote_name(table_name)} RESTART IDENTITY CASCADE")


def insert_rows(sqlite_cursor, table_name, columns, batch_size, replace):
    column_names = [column["name"] for column in columns]
    if not column_names:
        return 0

    sqlite_cursor.execute(f"SELECT {', '.join(quote_sqlite_identifier(name) for name in column_names)} FROM {quote_sqlite_identifier(table_name)}")
    placeholders = ", ".join(["%s"] * len(column_names))
    quoted_columns = ", ".join(quote_name(name) for name in column_names)
    pk_columns = [column["name"] for column in columns if column["pk"]]

    conflict_sql = ""
    if pk_columns and not replace:
        conflict_target = ", ".join(quote_name(name) for name in pk_columns)
        update_columns = [name for name in column_names if name not in pk_columns]
        if update_columns:
            updates = ", ".join(f"{quote_name(name)} = EXCLUDED.{quote_name(name)}" for name in update_columns)
            conflict_sql = f" ON CONFLICT ({conflict_target}) DO UPDATE SET {updates}"
        else:
            conflict_sql = f" ON CONFLICT ({conflict_target}) DO NOTHING"

    insert_sql = (
        f"INSERT INTO {quote_name(table_name)} ({quoted_columns}) "
        f"VALUES ({placeholders}){conflict_sql}"
    )

    imported = 0
    while True:
        rows = sqlite_cursor.fetchmany(batch_size)
        if not rows:
            break
        with connection.cursor() as cursor:
            cursor.executemany(insert_sql, rows)
        imported += len(rows)
    return imported


def reset_identity(table_name, columns):
    pk_columns = [column["name"] for column in columns if column["pk"] and "INT" in column["type"].upper()]
    if len(pk_columns) != 1:
        return
    pk_name = pk_columns[0]
    with connection.cursor() as cursor:
        cursor.execute("SELECT pg_get_serial_sequence(%s, %s)", [table_name, pk_name])
        sequence_row = cursor.fetchone()
        if not sequence_row or not sequence_row[0]:
            return
        cursor.execute(
            f"SELECT setval(%s, COALESCE((SELECT MAX({quote_name(pk_name)}) FROM {quote_name(table_name)}), 0) + 1, false)",
            [sequence_row[0]],
        )


class Command(BaseCommand):
    help = "Import unmanaged legacy tables from a SQLite database into the active PostgreSQL database."

    def add_arguments(self, parser):
        parser.add_argument("sqlite_path", help="Path to the source SQLite .db file.")
        parser.add_argument(
            "--replace",
            action="store_true",
            help="Truncate imported legacy tables before loading rows from SQLite.",
        )
        parser.add_argument(
            "--all-tables",
            action="store_true",
            help="Import every non-internal SQLite table instead of only unmanaged Django legacy tables.",
        )
        parser.add_argument(
            "--tables",
            help="Comma-separated table list to import. Overrides the default unmanaged legacy table list.",
        )
        parser.add_argument(
            "--require-tables",
            help="Comma-separated SQLite table names that must exist before import starts.",
        )
        parser.add_argument("--batch-size", type=int, default=500)
        parser.add_argument("--dry-run", action="store_true")

    def handle(self, *args, **options):
        sqlite_path = Path(options["sqlite_path"]).expanduser()
        if not sqlite_path.is_file():
            raise CommandError(f"SQLite database file does not exist or is not a file: {sqlite_path}")

        sqlite_connection = sqlite3.connect(f"file:{sqlite_path}?mode=ro", uri=True)
        try:
            sqlite_cursor = sqlite_connection.cursor()
            source_tables = sqlite_tables(sqlite_cursor)
            required_tables = {
                table.strip()
                for table in (options["require_tables"] or "").split(",")
                if table.strip()
            }
            missing_required_tables = sorted(required_tables - source_tables)
            if missing_required_tables:
                raise CommandError(
                    "Required table(s) missing from SQLite source: "
                    + ", ".join(missing_required_tables)
                )

            if options["tables"]:
                requested_tables = {table.strip() for table in options["tables"].split(",") if table.strip()}
            elif options["all_tables"]:
                requested_tables = source_tables
            else:
                requested_tables = unmanaged_model_tables()

            import_tables = sorted(source_tables & requested_tables)
            missing_tables = sorted(requested_tables - source_tables)
            if missing_tables:
                self.stdout.write(self.style.WARNING(f"Missing in SQLite, skipped: {', '.join(missing_tables)}"))
            if not import_tables:
                self.stdout.write(self.style.WARNING("No matching tables to import."))
                return

            self.stdout.write(f"Importing {len(import_tables)} table(s) into PostgreSQL.")
            if options["dry_run"]:
                for table_name in import_tables:
                    sqlite_cursor.execute(f"SELECT COUNT(*) FROM {quote_sqlite_identifier(table_name)}")
                    self.stdout.write(f"DRY RUN {table_name}: {sqlite_cursor.fetchone()[0]} row(s)")
                return

            if connection.vendor != "postgresql":
                raise CommandError("The target Django database must be PostgreSQL.")

            with transaction.atomic():
                for table_name in import_tables:
                    columns = sqlite_columns(sqlite_cursor, table_name)
                    create_or_extend_table(table_name, columns)
                    if options["replace"]:
                        reset_table(table_name)
                    imported = insert_rows(
                        sqlite_cursor,
                        table_name,
                        columns,
                        options["batch_size"],
                        options["replace"],
                    )
                    reset_identity(table_name, columns)
                    index_count = create_sqlite_indexes(sqlite_cursor, table_name)
                    self.stdout.write(self.style.SUCCESS(f"{table_name}: imported {imported} row(s), ensured {index_count} SQLite index(es)"))
                common_index_count = create_common_legacy_indexes(import_tables)
                if common_index_count:
                    self.stdout.write(self.style.SUCCESS(f"Ensured {common_index_count} common legacy PostgreSQL index(es)."))

            self.stdout.write(self.style.SUCCESS("SQLite legacy import completed."))
        finally:
            sqlite_connection.close()
