import re
import sqlite3
from pathlib import Path

from django.apps import apps
from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction


SAFE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
INTERNAL_PREFIXES = ("sqlite_",)


def quote_name(name):
    if not SAFE_IDENTIFIER.match(name):
        raise CommandError(f"Unsafe database identifier: {name!r}")
    return connection.ops.quote_name(name)


def sqlite_tables(sqlite_cursor):
    sqlite_cursor.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
        ORDER BY name
        """
    )
    return {
        row[0]
        for row in sqlite_cursor.fetchall()
        if not row[0].startswith(INTERNAL_PREFIXES)
    }


def unmanaged_model_tables():
    tables = set()
    for model in apps.get_models(include_auto_created=False):
        if not model._meta.managed:
            tables.add(model._meta.db_table)
    return tables


def sqlite_columns(sqlite_cursor, table_name):
    sqlite_cursor.execute(f"PRAGMA table_info({quote_sqlite_identifier(table_name)})")
    columns = []
    for row in sqlite_cursor.fetchall():
        columns.append(
            {
                "name": row[1],
                "type": row[2] or "",
                "notnull": bool(row[3]),
                "default": row[4],
                "pk": int(row[5] or 0),
            }
        )
    return columns


def quote_sqlite_identifier(name):
    if not SAFE_IDENTIFIER.match(name):
        raise CommandError(f"Unsafe SQLite identifier: {name!r}")
    return '"' + name.replace('"', '""') + '"'


def postgres_type(sqlite_type, is_primary_key=False):
    normalized = sqlite_type.upper()
    if "INT" in normalized:
        if is_primary_key:
            return "integer GENERATED BY DEFAULT AS IDENTITY"
        return "integer"
    if any(token in normalized for token in ("REAL", "FLOA", "DOUB")):
        return "double precision"
    if any(token in normalized for token in ("DEC", "NUM")):
        return "numeric"
    if "BLOB" in normalized:
        return "bytea"
    return "text"


def table_exists(table_name):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = %s
            """,
            [table_name],
        )
        return cursor.fetchone() is not None


def postgres_columns(table_name):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = %s
            """,
            [table_name],
        )
        return {row[0] for row in cursor.fetchall()}


def create_or_extend_table(table_name, columns):
    if not columns:
        return

    pk_columns = [column["name"] for column in columns if column["pk"]]
    with connection.cursor() as cursor:
        if not table_exists(table_name):
            definitions = []
            for column in columns:
                definition = f"{quote_name(column['name'])} {postgres_type(column['type'], bool(column['pk']))}"
                if column["notnull"] and not column["pk"]:
                    definition += " NOT NULL"
                definitions.append(definition)
            if pk_columns:
                pk_names = ", ".join(quote_name(name) for name in pk_columns)
                definitions.append(f"PRIMARY KEY ({pk_names})")
            cursor.execute(f"CREATE TABLE {quote_name(table_name)} ({', '.join(definitions)})")
            return

        existing_columns = postgres_columns(table_name)
        for column in columns:
            if column["name"] in existing_columns:
                continue
            cursor.execute(
                f"ALTER TABLE {quote_name(table_name)} "
                f"ADD COLUMN {quote_name(column['name'])} {postgres_type(column['type'], bool(column['pk']))}"
            )


def reset_table(table_name):
    with connection.cursor() as cursor:
        cursor.execute(f"TRUNCATE TABLE {quote_name(table_name)} RESTART IDENTITY CASCADE")


def insert_rows(sqlite_cursor, table_name, columns, batch_size, replace):
    column_names = [column["name"] for column in columns]
    if not column_names:
        return 0

    sqlite_cursor.execute(f"SELECT {', '.join(quote_sqlite_identifier(name) for name in column_names)} FROM {quote_sqlite_identifier(table_name)}")
    placeholders = ", ".join(["%s"] * len(column_names))
    quoted_columns = ", ".join(quote_name(name) for name in column_names)
    pk_columns = [column["name"] for column in columns if column["pk"]]

    conflict_sql = ""
    if pk_columns and not replace:
        conflict_target = ", ".join(quote_name(name) for name in pk_columns)
        update_columns = [name for name in column_names if name not in pk_columns]
        if update_columns:
            updates = ", ".join(f"{quote_name(name)} = EXCLUDED.{quote_name(name)}" for name in update_columns)
            conflict_sql = f" ON CONFLICT ({conflict_target}) DO UPDATE SET {updates}"
        else:
            conflict_sql = f" ON CONFLICT ({conflict_target}) DO NOTHING"

    insert_sql = (
        f"INSERT INTO {quote_name(table_name)} ({quoted_columns}) "
        f"VALUES ({placeholders}){conflict_sql}"
    )

    imported = 0
    while True:
        rows = sqlite_cursor.fetchmany(batch_size)
        if not rows:
            break
        with connection.cursor() as cursor:
            cursor.executemany(insert_sql, rows)
        imported += len(rows)
    return imported


def reset_identity(table_name, columns):
    pk_columns = [column["name"] for column in columns if column["pk"] and "INT" in column["type"].upper()]
    if len(pk_columns) != 1:
        return
    pk_name = pk_columns[0]
    with connection.cursor() as cursor:
        cursor.execute("SELECT pg_get_serial_sequence(%s, %s)", [table_name, pk_name])
        sequence_row = cursor.fetchone()
        if not sequence_row or not sequence_row[0]:
            return
        cursor.execute(
            f"SELECT setval(%s, COALESCE((SELECT MAX({quote_name(pk_name)}) FROM {quote_name(table_name)}), 0) + 1, false)",
            [sequence_row[0]],
        )


class Command(BaseCommand):
    help = "Import unmanaged legacy tables from a SQLite database into the active PostgreSQL database."

    def add_arguments(self, parser):
        parser.add_argument("sqlite_path", help="Path to the source SQLite .db file.")
        parser.add_argument(
            "--replace",
            action="store_true",
            help="Truncate imported legacy tables before loading rows from SQLite.",
        )
        parser.add_argument(
            "--all-tables",
            action="store_true",
            help="Import every non-internal SQLite table instead of only unmanaged Django legacy tables.",
        )
        parser.add_argument(
            "--tables",
            help="Comma-separated table list to import. Overrides the default unmanaged legacy table list.",
        )
        parser.add_argument("--batch-size", type=int, default=500)
        parser.add_argument("--dry-run", action="store_true")

    def handle(self, *args, **options):
        sqlite_path = Path(options["sqlite_path"]).expanduser()
        if not sqlite_path.exists():
            raise CommandError(f"SQLite file does not exist: {sqlite_path}")

        sqlite_connection = sqlite3.connect(f"file:{sqlite_path}?mode=ro", uri=True)
        try:
            sqlite_cursor = sqlite_connection.cursor()
            source_tables = sqlite_tables(sqlite_cursor)
            if options["tables"]:
                requested_tables = {table.strip() for table in options["tables"].split(",") if table.strip()}
            elif options["all_tables"]:
                requested_tables = source_tables
            else:
                requested_tables = unmanaged_model_tables()

            import_tables = sorted(source_tables & requested_tables)
            missing_tables = sorted(requested_tables - source_tables)
            if missing_tables:
                self.stdout.write(self.style.WARNING(f"Missing in SQLite, skipped: {', '.join(missing_tables)}"))
            if not import_tables:
                self.stdout.write(self.style.WARNING("No matching tables to import."))
                return

            self.stdout.write(f"Importing {len(import_tables)} table(s) into PostgreSQL.")
            if options["dry_run"]:
                for table_name in import_tables:
                    sqlite_cursor.execute(f"SELECT COUNT(*) FROM {quote_sqlite_identifier(table_name)}")
                    self.stdout.write(f"DRY RUN {table_name}: {sqlite_cursor.fetchone()[0]} row(s)")
                return

            if connection.vendor != "postgresql":
                raise CommandError("The target Django database must be PostgreSQL.")

            with transaction.atomic():
                for table_name in import_tables:
                    columns = sqlite_columns(sqlite_cursor, table_name)
                    create_or_extend_table(table_name, columns)
                    if options["replace"]:
                        reset_table(table_name)
                    imported = insert_rows(
                        sqlite_cursor,
                        table_name,
                        columns,
                        options["batch_size"],
                        options["replace"],
                    )
                    reset_identity(table_name, columns)
                    self.stdout.write(self.style.SUCCESS(f"{table_name}: imported {imported} row(s)"))

            self.stdout.write(self.style.SUCCESS("SQLite legacy import completed."))
        finally:
            sqlite_connection.close()
