# Generated by Django 6.0.6 on 2026-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimetableEntry',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('day_name', models.CharField(max_length=20)),
                ('day_order', models.IntegerField()),
                ('period_no', models.IntegerField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(max_length=120)),
                ('teacher_name', models.CharField(blank=True, max_length=180, null=True)),
                ('generated_by', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.TextField()),
                ('room_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'class_timetable_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ELearningAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('grade', models.CharField(max_length=80)),
                ('class_stream', models.CharField(blank=True, max_length=80, null=True)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.TextField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('status', models.CharField(default='Open', max_length=40)),
                ('uploaded_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'e_learning_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ELearningNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('grade', models.CharField(max_length=80)),
                ('class_stream', models.CharField(blank=True, max_length=80, null=True)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.TextField()),
            ],
            options={
                'db_table': 'e_learning_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ELearningSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('pupil_id', models.IntegerField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Submitted', max_length=40)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.TextField()),
                ('marked_by', models.IntegerField(blank=True, null=True)),
                ('marked_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'e_learning_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=40, unique=True)),
                ('subject_name', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=80)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=40)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
    ]
