# Generated by Django 6.0.6 on 2026-07-04 12:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fees_mgt_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zig_exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('operating_currency', models.CharField(choices=[('USD', 'USD'), ('ZIG', 'ZiG')], default='USD', max_length=10)),
            ],
            options={
                'db_table': 'fees_mgt_finance_settings',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('scholarships', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'db_table': 'fees_mgt_invoices',
                'ordering': ['-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_prefix', models.CharField(default='REC', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('last_receipt_no', models.IntegerField(default=0)),
                ('last_invoice_no', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fees_mgt_receipt_control',
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('O_LEVEL', 'Ordinary Level (Form 1-4)'), ('A_LEVEL', 'Advanced Level (Form 5-6)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_deadline', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academic_structure.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academic_structure.academicyear')),
            ],
            options={
                'db_table': 'fees_mgt_structures',
                'unique_together': {('academic_year', 'academic_term', 'level')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees_management.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees_management.invoice')),
            ],
            options={
                'db_table': 'fees_mgt_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('arrears', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='academic_structure.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='academic_structure.academicyear')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_accounts', to='fees_management.feestructure')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='student_registry.student')),
            ],
            options={
                'db_table': 'fees_mgt_student_accounts',
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=150)),
                ('sponsorship_type', models.CharField(choices=[('FULL_SCHOLARSHIP', 'Full Scholarship'), ('PARTIAL_SCHOLARSHIP', 'Partial Scholarship'), ('GOVERNMENT', 'Government Sponsorship'), ('NGO', 'NGO Sponsorship'), ('CORPORATE', 'Corporate Sponsorship'), ('PARENT', 'Parent Sponsorship')], max_length=40)),
                ('coverage_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='fees_management.studentfeeaccount')),
            ],
            options={
                'db_table': 'fees_mgt_sponsorships',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('instalment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_instalments', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_dates_json', models.JSONField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='fees_management.studentfeeaccount')),
            ],
            options={
                'db_table': 'fees_mgt_payment_plans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZIG', 'ZiG')], default='USD', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('amount_in_operating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees_management.studentfeeaccount')),
            ],
            options={
                'db_table': 'fees_mgt_payments',
                'ordering': ['-receipt_number'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='student_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='fees_management.studentfeeaccount'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED_AMOUNT', 'Fixed Amount Discount'), ('WAIVER', 'Fee Waiver')], max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_discounts_approved', to=settings.AUTH_USER_MODEL)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='fees_management.studentfeeaccount')),
            ],
            options={
                'db_table': 'fees_mgt_discounts',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('system_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discrepancy', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('RECONCILED', 'Reconciled'), ('DISCREPANCY', 'Discrepancy')], default='RECONCILED', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fees_mgt_reconciliations',
                'unique_together': {('reconciliation_date', 'payment_method')},
            },
        ),
    ]
