# Generated by Django 6.0.6 on 2026-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('user_role', models.CharField(blank=True, max_length=80, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=80, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=120, null=True)),
                ('request_method', models.CharField(blank=True, max_length=20, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackupLog',
            fields=[
                ('backup_id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_name', models.CharField(max_length=180)),
                ('backup_path', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'database_backups_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('setting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=180)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('school_phone', models.CharField(blank=True, max_length=80, null=True)),
                ('school_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('current_term', models.CharField(max_length=40)),
                ('current_year', models.IntegerField()),
                ('receipt_prefix', models.CharField(default='RCP', max_length=20)),
                ('whatsapp_sender_number', models.CharField(blank=True, max_length=40, null=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=120, null=True)),
                ('whatsapp_access_token', models.TextField(blank=True, null=True)),
                ('whatsapp_api_version', models.CharField(blank=True, max_length=30, null=True)),
                ('last_promotion_year', models.IntegerField(blank=True, null=True)),
                ('cashbook_opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'school_settings',
                'managed': False,
            },
        ),
    ]
