# Generated by Django 6.0.6 on 2026-07-10 07:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        ('student_registry', '0002_student_national_id_alter_student_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPickupPoint',
            fields=[
                ('pickup_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=150)),
                ('pickup_time', models.TimeField()),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'transport_pickup_points',
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(blank=True, help_text='e.g. Bus, minibus, SUV', max_length=50, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('fuel_type', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('current_mileage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance'), ('Out of Service', 'Out of Service'), ('Retired', 'Retired')], default='Active', max_length=30)),
            ],
            options={
                'db_table': 'transport_vehicles',
                'ordering': ['vehicle_name'],
            },
        ),
        migrations.CreateModel(
            name='TransportDriver',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('licence_number', models.CharField(max_length=50)),
                ('licence_expiry', models.DateField()),
                ('medical_expiry', models.DateField()),
                ('status', models.CharField(default='Active', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profiles', to='human_resources.employeeprofile')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.transportvehicle')),
            ],
            options={
                'db_table': 'transport_drivers',
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('route_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('route_code', models.CharField(max_length=30, unique=True)),
                ('route_name', models.CharField(max_length=100)),
                ('starting_point', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('distance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('estimated_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.transportdriver')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.transportvehicle')),
            ],
            options={
                'db_table': 'transport_routes',
                'ordering': ['route_code'],
            },
        ),
        migrations.CreateModel(
            name='TransportRegistration',
            fields=[
                ('registration_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('One-Way', 'One-Way'), ('Return Trip', 'Return Trip'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent')], default='Return Trip', max_length=30)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='transport.transportpickuppoint')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_registrations', to='student_registry.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='transport.transportroute')),
            ],
            options={
                'db_table': 'transport_registrations',
            },
        ),
        migrations.AddField(
            model_name='transportpickuppoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='transport.transportroute'),
        ),
        migrations.CreateModel(
            name='TransportMaintenance',
            fields=[
                ('maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Repair', 'Repair'), ('Insurance', 'Insurance'), ('Licence', 'Licence'), ('Tyre', 'Tyre')], max_length=30)),
                ('service_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='transport.transportvehicle')),
            ],
            options={
                'db_table': 'transport_maintenance',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportIncident',
            fields=[
                ('incident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportdriver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportvehicle')),
            ],
            options={
                'db_table': 'transport_incidents',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportFuelLog',
            fields=[
                ('fuel_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fuel_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='transport.transportvehicle')),
            ],
            options={
                'db_table': 'transport_fuel_logs',
                'ordering': ['-fuel_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportAttendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status_morning', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Sick', 'Sick'), ('Excused', 'Excused')], default='Present', max_length=20)),
                ('status_afternoon', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Sick', 'Sick'), ('Excused', 'Excused')], default='Present', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_registry.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportroute')),
            ],
            options={
                'db_table': 'transport_attendance',
                'unique_together': {('pupil', 'route', 'date')},
            },
        ),
    ]
