# Generated by Django 6.0.6 on 2026-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('pupil_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('attendance_date', models.TextField()),
                ('status', models.CharField(default='Present', max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('marked_by', models.IntegerField(blank=True, null=True)),
                ('marked_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'attendance_records',
                'managed': False,
            },
        ),
    ]
