# Generated by Django 6.0.6 on 2026-07-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIDataRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(max_length=80)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bi_data_refresh_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('module_code', models.CharField(max_length=80)),
                ('formula', models.TextField()),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('alert_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bi_kpi_definitions',
                'ordering': ['module_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('EXECUTIVE', 'Executive Dashboard'), ('ACADEMIC', 'Academic Dashboard'), ('FINANCIAL', 'Financial Dashboard'), ('HUMAN_RESOURCES', 'Human Resources Dashboard'), ('STUDENT', 'Student Dashboard'), ('PARENT', 'Parent Dashboard'), ('LIBRARY', 'Library Dashboard'), ('HOSTEL', 'Hostel Dashboard'), ('TRANSPORT', 'Transport Dashboard'), ('MEDICAL', 'Medical Dashboard'), ('SAAS', 'SaaS Administration Dashboard')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('permission_code', models.CharField(default='reports.view', max_length=120)),
                ('refresh_interval_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_dashboard_definitions',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('widget_type', models.CharField(choices=[('KPI_CARD', 'KPI Card'), ('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('LINE_GRAPH', 'Line Graph'), ('AREA_CHART', 'Area Chart'), ('HEAT_MAP', 'Heat Map'), ('TABLE', 'Table')], max_length=30)),
                ('metric_code', models.CharField(max_length=120)),
                ('data_source', models.CharField(max_length=120)),
                ('configuration', models.JSONField(default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='business_intelligence.dashboarddefinition')),
            ],
            options={
                'db_table': 'bi_dashboard_widgets',
                'ordering': ['dashboard', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('STUDENT_PERFORMANCE', 'Student Performance Prediction'), ('DROPOUT_RISK', 'Student Dropout Prediction'), ('FEE_COLLECTION', 'Fee Collection Forecasting'), ('ENROLMENT', 'Enrolment Forecasting'), ('RESOURCE_UTILISATION', 'Resource Utilisation Forecasting'), ('SAAS_CHURN', 'SaaS Churn Prediction')], max_length=40)),
                ('subject_reference', models.CharField(blank=True, max_length=160, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prediction', models.JSONField(default=dict)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_predictive_insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_report_execution_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('WORD', 'Word')], max_length=20)),
                ('file_name', models.CharField(max_length=180)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='business_intelligence.reportexecutionlog')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_report_exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('module_code', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('fields', models.JSONField(default=list)),
                ('filters', models.JSONField(default=dict)),
                ('default_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('WORD', 'Word')], default='PDF', max_length=20)),
                ('permission_code', models.CharField(default='reports.view', max_length=120)),
                ('is_system_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_report_templates',
                'ordering': ['module_code', 'name'],
                'unique_together': {('module_code', 'name')},
            },
        ),
        migrations.AddField(
            model_name='reportexecutionlog',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='business_intelligence.reporttemplate'),
        ),
        migrations.CreateModel(
            name='BIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('object_reference', models.CharField(blank=True, max_length=160, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_intelligence.dashboarddefinition')),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_intelligence.reporttemplate')),
            ],
            options={
                'db_table': 'bi_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filters', models.JSONField(default=dict)),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('WORD', 'Word')], default='PDF', max_length=20)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_bi_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='business_intelligence.reporttemplate')),
            ],
            options={
                'db_table': 'bi_saved_reports',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='reportexecutionlog',
            name='saved_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='business_intelligence.savedreport'),
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('NOTIFICATION', 'System Notification'), ('EMAIL', 'Email'), ('DOWNLOAD_CENTRE', 'Download Centre')], default='DOWNLOAD_CENTRE', max_length=30)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='business_intelligence.savedreport')),
            ],
            options={
                'db_table': 'bi_scheduled_reports',
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EXECUTIVE', 'Executive Dashboard'), ('ACADEMIC', 'Academic Dashboard'), ('FINANCIAL', 'Financial Dashboard'), ('HUMAN_RESOURCES', 'Human Resources Dashboard'), ('STUDENT', 'Student Dashboard'), ('PARENT', 'Parent Dashboard'), ('LIBRARY', 'Library Dashboard'), ('HOSTEL', 'Hostel Dashboard'), ('TRANSPORT', 'Transport Dashboard'), ('MEDICAL', 'Medical Dashboard'), ('SAAS', 'SaaS Administration Dashboard')], max_length=30)),
                ('snapshot_date', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bi_analytics_snapshots',
                'ordering': ['-snapshot_date', 'category'],
                'unique_together': {('category', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(default='ON_TRACK', max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='business_intelligence.kpidefinition')),
            ],
            options={
                'db_table': 'bi_kpi_snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('kpi', 'snapshot_date')},
            },
        ),
    ]
